language: r
dist: trusty
sudo: true
  
r:
#  - oldrel
  - release
#  - devel

os:
  - linux
#  - osx

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - RGL_USE_NULL=TRUE
  
warnings_are_errors: true

apt_packages:
  - gdal-bin
  - libgdal-dev
  - libgdal1-dev
  - libproj-dev
  - libgeos-dev
  - libgeos-c1
  - curl
  - libssh2-1-dev
  - qpdf
  - r-cran-rgdal
  - r-cran-rgl
  - r-cran-rgeos
  - valgrind

brew_packages:
  - Caskroom/cask/xquartz
  - ghostscript
  - valgrind

r_packages:
  - covr
  - rmarkdown
  - testthat

before_install: 
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript -e "setRepositories(ind=1:2);install.packages(c('rgdal','rgeos','RandomFieldsUtils','RandomFields','mvtnorm', 'gdalUtils'))"; fi;

script:
  - |
    R CMD build .
    travis_wait 40 R CMD check raptr*.tar.gz --as-cran --use-valgrind
  
after_success:
  - Rscript -e 'covr::codecov()'
 
notifications:
  email:
    on_success: change
    on_failure: change

