language: r
dist: trusty
sudo: true
  
r:
  - release
  - devel

os:
  - linux
  - osx

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - RGL_USE_NULL=TRUE
  
warnings_are_errors: true

apt_packages:
  - gdal-bin
  - libgdal-dev
  - libgdal1-dev
  - libproj-dev
  - libgeos-dev
  - libgeos-c1
  - curl
  - libssh2-1-dev
  - qpdf
  - r-cran-rgdal
  - r-cran-rgl
  - r-cran-rgeos

brew_packages:
  - Caskroom/cask/xquartz
  - ghostscript

r_packages:
  - covr
  - rmarkdown
  - testthat

before_install: 
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript -e "install.packages(c('adehabitatHR', 'BH', 'doParallel', 'ggplot2', 'hypervolume', 'ks', 'PBSmapping', 'plyr', 'RColorBrewer', 'RcppEigen', 'RgoogleMaps', 'scales', 'shape', 'shiny' 'curl', 'httr'))"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript -e "setRepositories(ind=1:2);install.packages(c('rgdal','rgeos','RandomFieldsUtils','RandomFields','mvtnorm', 'gdalUtils'))"; fi;
  
after_success:
  - Rscript -e 'covr::codecov()'
 
notifications:
  email:
    on_success: change
    on_failure: change

