language: r
sudo: required
warnings_are_errors: true
dist: trusty

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
  
r_check_args: --as-cran --use-gct --use-valgrind --timings

apt_packages:
  - libgeos-dev
  - libgeos-c1
  - curl
  - libssh2-1-dev
  - qpdf
  - r-cran-rgdal
  - r-cran-rgl
  - r-cran-rgeos

brew_packages:
  - Caskroom/cask/xquartz
  - ghostscript
  
before_install: 
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export RGL_USE_NULL=TRUE; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript -e "setRepositories(ind=1:2);install.packages(c('rgdal','rgeos','RandomFieldsUtils','RandomFields','mvtnorm', 'gdalUtils'))"; fi;

r_packages:
  - covr
  - rmarkdown
  - testthat
  
after_success:
  - Rscript -e 'covr::codecov()'
 
