language: r
sudo: required
warnings_are_errors: true

os:
  - linux
  - osx

env:
  global:
    - NOT_CRAN=true
    - _R_CHECK_FORCE_SUGGESTS_=False

apt_packages:
  - libgeos-dev
  - libgeos-c1    
    
before_install: 
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install r-cran-rgl -y; fi
  - if [ "$TRAVIS_OS_NAME" == "mac"]; then brew install Caskroom/cask/xquartz; fi;
  - if [ "$TRAVIS_OS_NAME" == "mac"]; then Rscript -e "install.packages(c('rgdal','rgeos'),repos='http://www.stats.ox.ac.uk/pub/RWin')"; fi;
  
r_binary_packages:
  - boot
  - PBSmapping
  - scales
  - shape
  - Matrix
  - adehabitatHR
  - RgoogleMaps
  - RandomFields
  - RColorBrewer
  - Rcpp
  - plyr
  - doSNOW
  - snow
  - hypervolume
  - sm
  - dismo
  - mvtnorm
  - sp
  - rgdal
  - raster

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  - jimhester/covr
  
after_success:
  - Rscript -e 'covr::codecov()'
 