# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

dist: xenial

warnings_are_errors: true

r_build_args: --no-build-vignettes

jobs:
  include:
    - os: osx
      r: release
      latex: false
    - os: linux
      r: release
      latex: true
    - os: linux
      r: devel
      latex: true

env:
  global:
    - RGL_USE_NULL=TRUE
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_packages:
  - covr
  - rmarkdown
  - testthat
  - devtools
  - Rcpp

before_install:
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y install gdal-bin libgdal-dev libgeos-dev mesa-common-dev libproj-dev libgl1-mesa-glx libglu1-mesa-dev libglu1-mesa libpng12-0 libx11-6 curl qpdf gdal-abi-2-2-2 libgdal20 libspatialite-dev libgeos-c1v5; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get clean; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get autoremove --purge; fi;
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get --purge remove tex.\*-doc$; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo Rscript -e "install.packages('tinytex');tinytex::install_tinytex()"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript -e "install.packages(c('rgdal','rgeos','RandomFieldsUtils','RandomFields','adehabitatHR','BH','doParallel','gdalUtils','ggplot2', 'hypervolume','ks','mvtnorm','PBSmapping','plyr','raster','RColorBrewer','RcppEigen','RgoogleMaps','scales','shape','rgl'),type='binary')"; fi;

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov()'; fi;

notifications:
  email:
    on_success: change
    on_failure: change
