# DO NOT CHANGE the "init" and "install" sections below

# set environmental variables
environment:
  WARNINGS_ARE_ERRORS: 1
  _R_CHECK_FORCE_SUGGESTS_: false
  R_CHECK_ARGS: --no-build-vignettes --no-manual 
  R_BUILD_ARGS: --no-build-vignettes --no-manual 
  CRAN: https://cran.csiro.au

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here
build_script:
  - R -e "options(repos=c(CRAN='https://cran.rstudio.com/')); install.packages('remotes'); suppressWarnings(remotes::install_deps(dependencies = TRUE, type = 'binary'))"

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
