// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_calcBoundaryDF
Rcpp::List rcpp_calcBoundaryDF(Rcpp::DataFrame df, double tolerance, double lengthFactor, double edgeFactor);
RcppExport SEXP raspr_rcpp_calcBoundaryDF(SEXP dfSEXP, SEXP toleranceSEXP, SEXP lengthFactorSEXP, SEXP edgeFactorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type lengthFactor(lengthFactorSEXP);
    Rcpp::traits::input_parameter< double >::type edgeFactor(edgeFactorSEXP);
    __result = Rcpp::wrap(rcpp_calcBoundaryDF(df, tolerance, lengthFactor, edgeFactor));
    return __result;
END_RCPP
}
// rcpp_groupcombine
NumericVector rcpp_groupcombine(std::vector<NumericVector> group_means);
RcppExport SEXP raspr_rcpp_groupcombine(SEXP group_meansSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<NumericVector> >::type group_means(group_meansSEXP);
    __result = Rcpp::wrap(rcpp_groupcombine(group_means));
    return __result;
END_RCPP
}
// rcpp_groupmean
NumericVector rcpp_groupmean(IntegerVector cat_vec, NumericVector val_vec);
RcppExport SEXP raspr_rcpp_groupmean(SEXP cat_vecSEXP, SEXP val_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type cat_vec(cat_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type val_vec(val_vecSEXP);
    __result = Rcpp::wrap(rcpp_groupmean(cat_vec, val_vec));
    return __result;
END_RCPP
}
// rcpp_Polygons2PolySet
Rcpp::DataFrame rcpp_Polygons2PolySet(Rcpp::List polys, std::size_t n_preallocate);
RcppExport SEXP raspr_rcpp_Polygons2PolySet(SEXP polysSEXP, SEXP n_preallocateSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type polys(polysSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_preallocate(n_preallocateSEXP);
    __result = Rcpp::wrap(rcpp_Polygons2PolySet(polys, n_preallocate));
    return __result;
END_RCPP
}
