<!-- Generated by staticdocs: do not edit by hand -->
<html>
  <head>
  <meta charset="utf-8">
<title>raptr: Representative and Adequate Prioritisation Toolkit in R. raptr</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>

<!-- Bootstrap -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



<!-- staticdocs -->
<link href="../staticdocs.css" rel="stylesheet">

<!-- mathjax -->
<script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>

<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
  </head>

  <body>
    <div class="container">
        <header>
        
<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../index.html">raptr</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">Home</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../articles/index.html">Articles</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/jeffreyhanson/raptr">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->
        
        </header>

        
<div class="row">
  <div class="col-md-9">
    <div class="page-header toc-ignore">
      <h1>raptr: Representative and Adequate Prioritisation Toolkit in R</h1>
            
            <h4 class="date"><em>24 October 2016</em></h4>
          </div>

    
    
<div id="overview" class="section level1">
<h1>Overview</h1>
<p>This vignette illustrates the basic usage of the <em>raptr R</em> package.</p>
<p>To load the <em>raptr R</em> package and learn more about the package, type the following code into R.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load raptr R package</span>
<span class="kw">library</span>(raptr)

<span class="co"># show package overview</span>
?raptr</code></pre></div>
<p>The <em>raptr R</em> package uses a range of S4 classes to store conservation planning data, parameters, and prioritisations (Table 1).</p>
<p>Table 1: Main classes in the <em>raptr R</em> package</p>
<table>
<colgroup>
<col width="20%" />
<col width="79%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"><strong>Class</strong></th>
<th align="left"><strong>Description</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><code>ManualOpts</code></td>
<td align="left">place-holder class for manually specified solutions</td>
</tr>
<tr class="even">
<td align="center"><code>GurobiOpts</code></td>
<td align="left">stores parameters for solving optimisation problems using <em>Gurobi</em></td>
</tr>
<tr class="odd">
<td align="center"><code>RapUnreliableOpts</code></td>
<td align="left">stores control variables parameters for the unreliable problem formulation</td>
</tr>
<tr class="even">
<td align="center"><code>RapReliableOpts</code></td>
<td align="left">stores control variables for the reliable problem formulation</td>
</tr>
<tr class="odd">
<td align="center"><code>DemandPoints</code></td>
<td align="left">stores the coordinates and weights for a given species and attribute space</td>
</tr>
<tr class="even">
<td align="center"><code>PlanningUnitPoints</code></td>
<td align="left">stores the coordinates and ids for planning units that can be used to preserve a given species</td>
</tr>
<tr class="odd">
<td align="center"><code>AttributeSpace</code></td>
<td align="left">stores the coordinates for planning units and the demand points for each species</td>
</tr>
<tr class="even">
<td align="center"><code>RapData</code></td>
<td align="left">stores the all the planning unit, species, and attribute space data</td>
</tr>
<tr class="odd">
<td align="center"><code>RapUnsolved</code></td>
<td align="left">stores all the data, control variables, and parameters needed to generate prioritisations</td>
</tr>
<tr class="even">
<td align="center"><code>RapResults</code></td>
<td align="left">stores the prioritisations and summary statistics generated after solving a problem</td>
</tr>
<tr class="odd">
<td align="center"><code>RapSolved</code></td>
<td align="left">stores the input data and output results</td>
</tr>
</tbody>
</table>
</div>
<div id="getting-started" class="section level1">
<h1>Getting started</h1>
<p>This tutorial is designed to provide users with an understanding of how to use the <em>raptr R</em> package to generate and compare solutions. This tutorial uses several additional packages, so first we will run the following code to load them.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load packages for tutorial</span>
<span class="kw">library</span>(parallel)
<span class="kw">library</span>(plyr)
<span class="kw">library</span>(dplyr)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(RandomFields)
<span class="kw">library</span>(rgeos)

<span class="co"># set seed for reproducibility</span>
<span class="kw">set.seed</span>(<span class="dv">500</span>)

<span class="co"># set number of threads for computation</span>
threads &lt;-<span class="st"> </span><span class="kw">as.integer</span>(<span class="kw">max</span>(<span class="dv">1</span>, <span class="kw">detectCores</span>()-<span class="dv">2</span>))</code></pre></div>
</div>
<div id="simulated-examples" class="section level1">
<h1>Simulated examples</h1>
<div id="data" class="section level2">
<h2>Data</h2>
<p>To investigate the behaviour of the problem, we will generate prioritisations for three simulated species. We will use the unreliable formulation of the problem to understand the basics, and later move onto the reliable formulation. The first species (termed ‘uniform’) will represent a hyper-generalist. This species will inhabit all areas with equal probability. The second species (termed ‘normal’) will represent a species with a single range core. The third species (termed ‘bimodal’) will represent a species with two distinct ecotypes, each with their own range core. To reduce computational time for this example, we will use a 10 <span class="math inline">\(\times\)</span> 10 grid of square planning units.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make planning units</span>
sim_pus &lt;-<span class="st"> </span><span class="kw">sim.pus</span>(100L)

<span class="co"># simulate species distributions</span>
sim_spp &lt;-<span class="st"> </span><span class="kw">lapply</span>(
    <span class="kw">c</span>(<span class="st">&#39;uniform&#39;</span>, <span class="st">&#39;normal&#39;</span>, <span class="st">&#39;bimodal&#39;</span>),
    sim.species,
    <span class="dt">n=</span><span class="dv">1</span>,
    <span class="dt">x=</span>sim_pus,
    <span class="dt">res=</span><span class="dv">1</span>
)</code></pre></div>
<p>Let’s see what these species’ distributions look like.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot species</span>
<span class="kw">plot</span>(
    <span class="kw">stack</span>(sim_spp),
    <span class="dt">main=</span><span class="kw">c</span>(<span class="st">&#39;Uniform species&#39;</span>,<span class="st">&#39;Normal species&#39;</span>,<span class="st">&#39;Bimodal species&#39;</span>),
    <span class="dt">addfun=</span>function(){<span class="kw">lines</span>(sim_pus)},
    <span class="dt">nc=</span><span class="dv">3</span>
)</code></pre></div>
<div class="figure">
<img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-4-1.png" alt="Distribution of three simulated species. Each square represents a planning unit. The colour of each square denotes the probability that individuals from each species occupy it." />
<p class="caption"><em>Distribution of three simulated species. Each square represents a planning unit. The colour of each square denotes the probability that individuals from each species occupy it.</em></p>
</div>
<p>Next, we will generate a set of demand points. To understand the effects of probabilities and weights on the demand points, we will generate the demand points in geographic space. These demand points will be the centroids of the planning units. Additionally, we will use the same set of demand points for each species and only vary the weights of the demand points between species. <strong>Note that we are only using the same distribution of demand points for different species for teaching purposes. It is strongly recommended to use different demand points for different species in real-world conservation planning exercises.</strong> See the case-study section of this tutorial for examples on how to generate suitable demand points.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># generate coordinates for pus/demand points</span>
pu_coords &lt;-<span class="st"> </span><span class="kw">gCentroid</span>(sim_pus, <span class="dt">byid=</span><span class="ot">TRUE</span>)

<span class="co"># calculate weights</span>
sim_dps &lt;-<span class="st"> </span><span class="kw">lapply</span>(
    sim_spp,
    function(x) {
        <span class="kw">return</span>(<span class="kw">extract</span>(x, pu_coords))
    }
)

<span class="co"># create demand point objects</span>
sim_dps &lt;-<span class="st"> </span><span class="kw">lapply</span>(
    sim_dps,
    function(x) {
        <span class="kw">return</span>(
            <span class="kw">DemandPoints</span>(
                pu_coords@coords,
                <span class="dt">weights=</span><span class="kw">c</span>(x)
            )
        )
    }
)</code></pre></div>
<p>Now, we will construct a <code>RapUnsolved</code> object to store our input data and parameters. This contains all the information to generate prioritisations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## create RapUnreliableOpts object
<span class="co"># this stores parameters for the unreliable formulation problem (ie. BLM)</span>
sim_ro &lt;-<span class="st"> </span><span class="kw">RapUnreliableOpts</span>()

## create RapData object
<span class="co"># create data.frame with species info</span>
species &lt;-<span class="st"> </span><span class="kw">data.frame</span>(
    <span class="dt">name=</span><span class="kw">c</span>(<span class="st">&#39;uniform&#39;</span>, <span class="st">&#39;normal&#39;</span>, <span class="st">&#39;bimodal&#39;</span>)
)

## create data.frame with species and space targets
<span class="co"># amount targets at 20% (denoted with target=0)</span>
<span class="co"># space targets at 20% (denoted with target=1)</span>
targets &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(
    <span class="dt">species=</span><span class="dv">1</span>:<span class="dv">3</span>,
    <span class="dt">target=</span><span class="dv">0</span>:<span class="dv">1</span>,
    <span class="dt">proportion=</span><span class="fl">0.2</span>
)

<span class="co"># calculate probability of each species in each pu</span>
pu_probabilities &lt;-<span class="st"> </span><span class="kw">calcSpeciesAverageInPus</span>(sim_pus, <span class="kw">stack</span>(sim_spp))

## create AttributeSpace object
<span class="co"># this stores the coordinates of the planning units in an attribute space</span>
<span class="co"># and the coordinates and weights of demand points in the space</span>

pu_points &lt;-<span class="st"> </span><span class="kw">PlanningUnitPoints</span>(
    <span class="dt">coords=</span>pu_coords@coords,
    <span class="dt">ids=</span><span class="kw">seq_len</span>(<span class="kw">nrow</span>(sim_pus@data))
)

attr_spaces &lt;-<span class="st"> </span><span class="kw">AttributeSpaces</span>(
    <span class="kw">list</span>(
        <span class="kw">AttributeSpace</span>(
            <span class="dt">planning.unit.points=</span>pu_points,
            <span class="dt">demand.points=</span>sim_dps[[<span class="dv">1</span>]],
            <span class="dt">species=</span>1L
        ),
        <span class="kw">AttributeSpace</span>(
            <span class="dt">planning.unit.points=</span>pu_points,
            <span class="dt">demand.points=</span>sim_dps[[<span class="dv">2</span>]],
            <span class="dt">species=</span>2L
        ),
        <span class="kw">AttributeSpace</span>(
            <span class="dt">planning.unit.points=</span>pu_points,
            <span class="dt">demand.points=</span>sim_dps[[<span class="dv">3</span>]],
            <span class="dt">species=</span>3L
        )
    ),
    <span class="dt">name=</span><span class="st">&#39;geographic&#39;</span>
)

<span class="co"># generate boundary data information</span>
boundary &lt;-<span class="st"> </span><span class="kw">calcBoundaryData</span>(sim_pus)

## create RapData object
<span class="co"># this stores all the input data for the prioritisation</span>
sim_rd &lt;-<span class="st"> </span><span class="kw">RapData</span>(
    sim_pus@data,
    species,
    targets,
    pu_probabilities,
    <span class="kw">list</span>(attr_spaces),
    boundary,
    <span class="kw">SpatialPolygons2PolySet</span>(sim_pus)
)

## create RapUnsolved object
<span class="co"># this stores all the input data and parameters needed to generate prioritisations</span>
sim_ru &lt;-<span class="st"> </span><span class="kw">RapUnsolved</span>(sim_ro, sim_rd)</code></pre></div>
</div>
<div id="single-species-prioritisations" class="section level2">
<h2>Single-species prioritisations</h2>
<div id="amount-based-targets" class="section level3">
<h3>Amount-based targets</h3>
<p>To investigate the effects of space-based targets, we will generate a prioritisation for each species using only amount-based targets and compare them to prioritisations generated using amount- and space-based targets. To start off, we will generate a prioritisation for the uniform species using amount-based targets. To do this, we will generate a new <code>sim_ru</code> object by subsetting out the data for the uniform species from the <code>sim_ru</code> object. Then, we will update the targets in the new object. Finally, we will solve the object to generate a prioritisation that fulfills the targets for minimal cost.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create new object with just the uniform species</span>
sim_ru_s1 &lt;-<span class="st"> </span><span class="kw">spp.subset</span>(sim_ru, <span class="st">&#39;uniform&#39;</span>)

<span class="co"># update amount targets to 20% and space targets to 0%</span>
sim_ru_s1 &lt;-<span class="st"> </span><span class="kw">update</span>(sim_ru_s1, <span class="dt">amount.target=</span><span class="fl">0.2</span>, <span class="dt">space.target=</span><span class="ot">NA</span>, <span class="dt">solve=</span><span class="ot">FALSE</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># solve problem to identify prioritisation</span>
sim_rs_s1_amount &lt;-<span class="st"> </span><span class="kw">solve</span>(sim_ru_s1, <span class="dt">Threads=</span>threads)</code></pre></div>
<pre><code>## Optimize a model with 1 rows, 100 columns and 100 nonzeros
## Coefficient statistics:
##   Matrix range    [5e-01, 5e-01]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [1e+01, 1e+01]
## Found heuristic solution: objective 20
## Presolve removed 1 rows and 100 columns
## Presolve time: 0.00s
## Presolve: All rows and columns removed
## 
## Explored 0 nodes (0 simplex iterations) in 0.00 seconds
## Thread count was 1 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 2.000000000000e+01, best bound 2.000000000000e+01, gap 0.0%</code></pre>
<pre><code>## Warning in validityMethod(object): object@space.held contains values less
## than 0, some species are really poorly represented</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## show summary
<span class="co"># note the format for this is similar to that used by Marxan</span>
<span class="co"># see ?raptr::summary for details on this table</span>
<span class="kw">summary</span>(sim_rs_s1_amount)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL    20   20             20                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1              42               168               10
##   Connectivity_In_Fraction
## 1                0.1909091</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show amount held</span>
<span class="kw">amount.held</span>(sim_rs_s1_amount)</code></pre></div>
<pre><code>##   uniform
## 1     0.2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show space held</span>
<span class="kw">space.held</span>(sim_rs_s1_amount)</code></pre></div>
<pre><code>##   uniform (Space 1)
## 1        -0.2363636</code></pre>
<p>Now that we have generated a prioritisation, let’s see what it looks like. We can use the <code>spp.plot</code> method to see how the prioritisation overlaps with the uniform species’ distribution. Note that since all planning units have equal probabilities for this species, all planning units have the same fill colour.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the prioritisation and the uniform species&#39; distribution</span>
<span class="kw">spp.plot</span>(sim_rs_s1_amount, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Uniform species&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-10-1.png" title="_A prioritisation for the uniformly distributed species generated using amount-based targets (20\%). Sqaures represent planning units. Planning units with a green border are selected for prioritisation, and their colour denotes the probability they are inhabited by the species._" alt="_A prioritisation for the uniformly distributed species generated using amount-based targets (20\%). Sqaures represent planning units. Planning units with a green border are selected for prioritisation, and their colour denotes the probability they are inhabited by the species._" style="display: block; margin: auto;" /></p>
<p>The prioritisation for the uniform species appears to be just a random selection of planning units. This behavior is due to the fact that any prioritisation with 20 planning units is optimal. By relying on just amount targets, this solution may preserve a section of the species’ range core, or just focus on the range margin, or some random part of its range–no emphasis is directed towards preserving different parts of the species’ range. This behavior highlights a fundamental limitation of just using amount-based targets. In the absence of additional criteria, conventional reserve selection problems do not contain any additional information to identify the most effective prioritisation.</p>
<p>Now, we will generate a prioritisation for the normally distributed species using amount-based targets. We will use a similar process to what we used for the uniformly distributed species, but for brevity, we will use code to generate solutions immediately after updating the object.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create new object with just the normal species</span>
sim_ru_s2 &lt;-<span class="st"> </span><span class="kw">spp.subset</span>(sim_ru, <span class="st">&#39;normal&#39;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># update amount targets to 20% and space targets to 0% and solve it</span>
sim_rs_s2_amount &lt;-<span class="st"> </span><span class="kw">update</span>(sim_ru_s2, <span class="dt">amount.target=</span><span class="fl">0.2</span>, <span class="dt">space.target=</span><span class="ot">NA</span>, <span class="dt">solve=</span><span class="ot">TRUE</span>, <span class="dt">Threads=</span>threads)</code></pre></div>
<pre><code>## Optimize a model with 1 rows, 100 columns and 100 nonzeros
## Coefficient statistics:
##   Matrix range    [7e-02, 7e-01]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [7e+00, 7e+00]
## Found heuristic solution: objective 27
## Presolve removed 0 rows and 86 columns
## Presolve time: 0.00s
## Presolved: 1 rows, 14 columns, 14 nonzeros
## Variable types: 0 continuous, 14 integer (0 binary)
## Presolved: 1 rows, 14 columns, 14 nonzeros
## 
## 
## Root relaxation: objective 9.864476e+00, 6 iterations, 0.00 seconds
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
##      0     0    9.86448    0    1   27.00000    9.86448  63.5%     -    0s
## H    0     0                      10.0000000    9.86448  1.36%     -    0s
## 
## Explored 0 nodes (6 simplex iterations) in 0.00 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 1.000000000000e+01, best bound 1.000000000000e+01, gap 0.0%</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summary</span>
<span class="kw">summary</span>(sim_rs_s2_amount)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL    10   10             10                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1              12               192               16
##   Connectivity_In_Fraction
## 1               0.05454545</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show amount held</span>
<span class="kw">amount.held</span>(sim_rs_s2_amount)</code></pre></div>
<pre><code>##      normal
## 1 0.2026153</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show space held</span>
<span class="kw">space.held</span>(sim_rs_s2_amount)</code></pre></div>
<pre><code>##   normal (Space 1)
## 1        0.5909494</code></pre>
<p>Now let’s visualise the prioritisation we made for the normal species.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the prioritisation and the normal species&#39; distribution</span>
<span class="kw">spp.plot</span>(sim_rs_s2_amount, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Normal species&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-14-1.png" title="_A prioritisation for the normally distributed species generated using amount-based targets (20\%). See Figure 3 caption for conventions._" alt="_A prioritisation for the normally distributed species generated using amount-based targets (20\%). See Figure 3 caption for conventions._" style="display: block; margin: auto;" /></p>
<p>The amount-based prioritisation for the normal species focuses only on the species’ range core. This prioritisation fails to secure any peripheral parts of the species’ distribution. As a consequence, it may miss out on populations with novel adaptations to environmental conditions along the species’ range margin.</p>
<p>Now, let’s generate an amount-based target for the bimodally distributed species view it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create new object with just the bimodal species</span>
sim_ru_s3 &lt;-<span class="st"> </span><span class="kw">spp.subset</span>(sim_ru, <span class="st">&#39;bimodal&#39;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># update amount targets to 20% and space targets to 0% and solve it</span>
sim_rs_s3_amount &lt;-<span class="st"> </span><span class="kw">update</span>(sim_ru_s3, <span class="dt">amount.target=</span><span class="fl">0.2</span>, <span class="dt">space.target=</span><span class="ot">NA</span>, <span class="dt">Threads=</span>threads)</code></pre></div>
<pre><code>## Optimize a model with 1 rows, 100 columns and 100 nonzeros
## Coefficient statistics:
##   Matrix range    [7e-03, 9e-01]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [7e+00, 7e+00]
## Found heuristic solution: objective 21
## Presolve removed 0 rows and 75 columns
## Presolve time: 0.00s
## Presolved: 1 rows, 25 columns, 25 nonzeros
## Variable types: 0 continuous, 25 integer (0 binary)
## Presolved: 1 rows, 25 columns, 25 nonzeros
## 
## 
## Root relaxation: objective 7.919039e+00, 18 iterations, 0.00 seconds
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
##      0     0    7.91904    0    1   21.00000    7.91904  62.3%     -    0s
## H    0     0                       8.0000000    7.91904  1.01%     -    0s
## 
## Explored 0 nodes (18 simplex iterations) in 0.00 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 8.000000000000e+00, best bound 8.000000000000e+00, gap 0.0%</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the prioritisation and the bimodal species&#39; distribution</span>
<span class="kw">spp.plot</span>(sim_rs_s3_amount, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Bimodal species&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-17-1.png" title="_A prioritisation for the bimodally distributed species generated using amount-based targets (20\%). See Figure 3 caption for conventions._" alt="_A prioritisation for the bimodally distributed species generated using amount-based targets (20\%). See Figure 3 caption for conventions._" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summary</span>
<span class="kw">summary</span>(sim_rs_s3_amount)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL     8    8              8                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1               9               197               14
##   Connectivity_In_Fraction
## 1               0.04090909</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show amount held</span>
<span class="kw">amount.held</span>(sim_rs_s3_amount)</code></pre></div>
<pre><code>##     bimodal
## 1 0.2018391</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show space held</span>
<span class="kw">space.held</span>(sim_rs_s3_amount)</code></pre></div>
<pre><code>##   bimodal (Space 1)
## 1         0.1200278</code></pre>
<p>The amount-based prioritisation for the bimodally distributed species only selects planning units in the bottom left corner of the study area. This prioritisation only preserves individuals belonging to one of the two ecotypes. As a consequence, this prioritisation may fail to preserve a representative sample of the genetic variation found inside this species.</p>
</div>
<div id="amount-based-and-space-based-targets" class="section level3">
<h3>Amount-based and space-based targets</h3>
<p>Now that we have generated a prioritisation for each species using only amount-based targets, we will generate a prioritisations using both amount-based and space-targets. To do this we will update the space targets in our amount-based prioritisations to 85%, and store the new prioritisations in new objects.</p>
<p>First, let’s do this for the uniform species.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make new prioritisation</span>
sim_rs_s1_space &lt;-<span class="st"> </span><span class="kw">update</span>(sim_rs_s1_amount, <span class="dt">amount.target=</span><span class="fl">0.2</span>, <span class="dt">space.target=</span><span class="fl">0.85</span>, <span class="dt">Threads=</span>threads)</code></pre></div>
<pre><code>## Warning for adding variables: zero or small (&lt; 1e-13) coefficients, ignored
## Optimize a model with 10102 rows, 10100 columns and 40000 nonzeros
## Coefficient statistics:
##   Matrix range    [5e-01, 8e+01]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [1e+00, 1e+02]
## Found heuristic solution: objective 88
## Presolve removed 36 rows and 0 columns
## Presolve time: 2.19s
## Presolved: 10066 rows, 10100 columns, 40104 nonzeros
## Variable types: 0 continuous, 10100 integer (10100 binary)
## Presolved: 10066 rows, 10100 columns, 40104 nonzeros
## 
## Presolve removed 10066 rows and 10100 columns
## 
## Root relaxation: objective 2.000000e+01, 621 iterations, 0.09 seconds
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
## *    0     0               0      20.0000000   20.00000  0.00%     -    2s
## 
## Explored 0 nodes (1086 simplex iterations) in 2.36 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 2.000000000000e+01, best bound 2.000000000000e+01, gap 0.0%</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summary</span>
<span class="kw">summary</span>(sim_rs_s1_space)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL    20   20             20                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1               8               143               69
##   Connectivity_In_Fraction
## 1               0.03636364</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show amount held</span>
<span class="kw">amount.held</span>(sim_rs_s1_space)</code></pre></div>
<pre><code>##   uniform
## 1     0.2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show space held</span>
<span class="kw">space.held</span>(sim_rs_s1_space)</code></pre></div>
<pre><code>##   uniform (Space 1)
## 1         0.9309091</code></pre>
<p>Let’s take a look at the prioritisation for the uniform species with amount-based and space-based targets. Then, let’s compare the solutions for the amount-based prioritisation with the new prioritisation using both amount and space targets.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the prioritisation and the uniform species&#39; distribution</span>
<span class="kw">spp.plot</span>(sim_rs_s1_space, <span class="st">&#39;uniform&#39;</span>, <span class="dt">main=</span><span class="st">&#39;Uniform species&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-21-1.png" title="_A prioritisation for the uniformly distributed species generated using amount-based targets (20\%) and space-based targets (85\%). See Figure 3 caption for conventions._" alt="_A prioritisation for the uniformly distributed species generated using amount-based targets (20\%) and space-based targets (85\%). See Figure 3 caption for conventions._" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the difference between old and new prioritisations</span>
<span class="kw">plot</span>(sim_rs_s1_amount, sim_rs_s1_space, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Difference between solutions&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-22-1.png" title="_Difference between two prioritisations for the uniformly distributed species. Prioritisation $X$ was generated using just amount-based targets (20\%), and prioritisation $Y$ was generated using an additional space-based target (85\%)._" alt="_Difference between two prioritisations for the uniformly distributed species. Prioritisation $X$ was generated using just amount-based targets (20\%), and prioritisation $Y$ was generated using an additional space-based target (85\%)._" style="display: block; margin: auto;" /></p>
<p>Here we can see that by including a space-target, the prioritisation is spread out evenly across the species’ distribution. Unlike the amount-based prioritisation, this prioritisation samples all the different parts of the species’ distribution.</p>
<p>Now, let’s generate a prioritisation for the normally distributed species that considers amount-based and space-based targets. Then, let’s visualise the new prioritisation and compare it to the old amount-based prioritisation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make new prioritisation</span>
sim_rs_s2_space &lt;-<span class="st"> </span><span class="kw">update</span>(sim_rs_s2_amount, <span class="dt">amount.target=</span><span class="fl">0.2</span>, <span class="dt">space.target=</span><span class="fl">0.85</span>, <span class="dt">Threads=</span>threads)</code></pre></div>
<pre><code>## Warning for adding variables: zero or small (&lt; 1e-13) coefficients, ignored
## Optimize a model with 10102 rows, 10100 columns and 40000 nonzeros
## Coefficient statistics:
##   Matrix range    [7e-02, 4e+01]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [1e+00, 6e+01]
## Found heuristic solution: objective 91
## Presolve removed 220 rows and 0 columns
## Presolve time: 1.58s
## Presolved: 9882 rows, 10100 columns, 41664 nonzeros
## Variable types: 0 continuous, 10100 integer (10100 binary)
## Presolved: 9882 rows, 10100 columns, 41664 nonzeros
## 
## Presolve removed 9882 rows and 10100 columns
## 
## Root relaxation: objective 1.232570e+01, 4135 iterations, 0.28 seconds
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
##      0     0   12.32570    0  290   91.00000   12.32570  86.5%     -    1s
## H    0     0                      13.0000000   12.32570  5.19%     -    2s
## 
## Explored 0 nodes (4369 simplex iterations) in 2.03 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 1.300000000000e+01, best bound 1.300000000000e+01, gap 0.0%</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summary</span>
<span class="kw">summary</span>(sim_rs_s2_space)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL    13   13             13                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1               5               173               42
##   Connectivity_In_Fraction
## 1               0.02272727</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show amount held</span>
<span class="kw">amount.held</span>(sim_rs_s2_space)</code></pre></div>
<pre><code>##      normal
## 1 0.2014166</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show space held</span>
<span class="kw">space.held</span>(sim_rs_s2_space)</code></pre></div>
<pre><code>##   normal (Space 1)
## 1          0.85809</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the prioritisation and the normal species&#39; distribution</span>
<span class="kw">spp.plot</span>(sim_rs_s2_space, <span class="st">&#39;normal&#39;</span>, <span class="dt">main=</span><span class="st">&#39;Normal species&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-25-1.png" title="_A prioritisation for the normally distributed species generated using amount-based targets (20\%) and space-based targets (85\%). See Figure 3 caption for conventions._" alt="_A prioritisation for the normally distributed species generated using amount-based targets (20\%) and space-based targets (85\%). See Figure 3 caption for conventions._" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the difference between old and new prioritisations</span>
<span class="kw">plot</span>(sim_rs_s2_amount, sim_rs_s2_space, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Difference between solutions&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-26-1.png" title="_Difference between two prioritisations for the normally distributed species. See Figure 7 caption for conventions._" alt="_Difference between two prioritisations for the normally distributed species. See Figure 7 caption for conventions._" style="display: block; margin: auto;" /></p>
<p>We can see by using both amount-based and space-based targets we can obtain a prioritisation that secures both the species’ range core and parts of its range margin. As a consequence, it may capture any novel adaptations found along the species’ range margin–unlike the amount-based prioritisation.</p>
<p>Finally, let’s generate a prioritisation for the bimodal species using amount-based and space-based targets.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make new prioritisation</span>
sim_rs_s3_space &lt;-<span class="st"> </span><span class="kw">update</span>(sim_rs_s3_amount, <span class="dt">amount.target=</span><span class="fl">0.2</span>, <span class="dt">space.target=</span><span class="fl">0.85</span>, <span class="dt">Threads=</span>threads)</code></pre></div>
<pre><code>## Warning for adding variables: zero or small (&lt; 1e-13) coefficients, ignored
## Optimize a model with 10102 rows, 10100 columns and 40000 nonzeros
## Coefficient statistics:
##   Matrix range    [7e-03, 9e+01]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [1e+00, 7e+01]
## Found heuristic solution: objective 86
## Presolve removed 589 rows and 15 columns
## Presolve time: 3.67s
## Presolved: 9513 rows, 10085 columns, 51461 nonzeros
## Variable types: 0 continuous, 10085 integer (10085 binary)
## Presolved: 9513 rows, 10085 columns, 51461 nonzeros
## 
## Presolve removed 9513 rows and 10085 columns
## 
## Root relaxation: objective 8.980792e+00, 6437 iterations, 0.44 seconds
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
##      0     0    8.98079    0   75   86.00000    8.98079  89.6%     -    4s
## H    0     0                      10.0000000    8.98079  10.2%     -    4s
##      0     0    8.99662    0  125   10.00000    8.99662  10.0%     -    4s
## 
## Cutting planes:
##   Gomory: 1
##   Zero half: 1
## 
## Explored 0 nodes (6761 simplex iterations) in 4.70 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 1.000000000000e+01, best bound 1.000000000000e+01, gap 0.0%</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summary</span>
<span class="kw">summary</span>(sim_rs_s3_space)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL    10   10             10                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1               6               186               28
##   Connectivity_In_Fraction
## 1               0.02727273</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show amount held</span>
<span class="kw">amount.held</span>(sim_rs_s3_space)</code></pre></div>
<pre><code>##     bimodal
## 1 0.2127869</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show space held</span>
<span class="kw">space.held</span>(sim_rs_s3_space)</code></pre></div>
<pre><code>##   bimodal (Space 1)
## 1         0.8650189</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the prioritisation and the bimodal species&#39; distribution</span>
<span class="kw">spp.plot</span>(sim_rs_s3_space, <span class="st">&#39;bimodal&#39;</span>, <span class="dt">main=</span><span class="st">&#39;Bimodal species&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-29-1.png" title="_A prioritisation for the normally distributed species generated using amount-based targets (20\%) and space-based targets (85\%). See Figure 3 caption for conventions._" alt="_A prioritisation for the normally distributed species generated using amount-based targets (20\%) and space-based targets (85\%). See Figure 3 caption for conventions._" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the difference between old and new prioritisations</span>
<span class="kw">plot</span>(sim_rs_s3_amount, sim_rs_s3_space, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Difference between solutions&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-30-1.png" title="_Difference between two prioritisations for the bimodally distributed species. See Figure 7 caption for conventions._" alt="_Difference between two prioritisations for the bimodally distributed species. See Figure 7 caption for conventions._" style="display: block; margin: auto;" /></p>
<p>Earlier we found that the amount-based prioritisation only preserved individuals from a single ecotype, and would have failed to adequately preserve the intra-specific variation for this species. However, here we can see that by including space-based targets, we can develop prioritisations that secure individuals belonging to both ecotypes. This new prioritisation is much more effective at sampling the intra-specific variation for this species.</p>
<p>Overall, these results demonstrate that under the simplest of conditions, the use of space-based targets can improve prioritisations. However, these prioritisations were each generated for a single species. Prioritisations generated using multiple species may do a better job at preserving the intra-specific variation for individuals species by preserving them in different parts of their range. We will investigate this in the next section.</p>
</div>
</div>
<div id="multi-species-prioritisations" class="section level2">
<h2>Multi-species prioritisations</h2>
<div id="effects-of-including-space-based-targets" class="section level3">
<h3>Effects of including space-based targets</h3>
<p>So far we have generated prioritisations using only a single species at a time. However, real world prioritisations are often generated using multiple species to ensure that they preserve a comprehensive set of biodiversity. Here, we will generate multi-species prioritisations that preserve all three of the simulated species. First, we will generate a prioritisation using amount-based targets that only aims to preserve 20% of the area they occupy. Then, we will generate a prioritisation that also incoperate space-based targets to also preserve 85% of their geographic distribution. We will then compare the two prioritisations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make prioritisations</span>
sim_mrs_amount &lt;-<span class="st"> </span><span class="kw">update</span>(
    sim_ru,
    <span class="dt">amount.target=</span><span class="kw">c</span>(<span class="fl">0.2</span>,<span class="fl">0.2</span>,<span class="fl">0.2</span>),
    <span class="dt">space.target=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>),
    <span class="dt">Threads=</span>threads
)</code></pre></div>
<pre><code>## Warning for adding variables: zero or small (&lt; 1e-13) coefficients, ignored
## Optimize a model with 30306 rows, 30100 columns and 120000 nonzeros
## Coefficient statistics:
##   Matrix range    [7e-03, 9e+01]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [1e+00, 8e+02]
## Found heuristic solution: objective 98
## Presolve time: 1.35s
## Presolved: 30306 rows, 30100 columns, 120000 nonzeros
## Variable types: 0 continuous, 30100 integer (30100 binary)
## Presolved: 30306 rows, 30100 columns, 120000 nonzeros
## 
## Presolve removed 30306 rows and 30100 columns
## 
## Root relaxation: objective 2.000000e+01, 2021 iterations, 1.90 seconds
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
## *    0     0               0      20.0000000   20.00000  0.00%     -    3s
## 
## Explored 0 nodes (4785 simplex iterations) in 3.92 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 2.000000000000e+01, best bound 2.000000000000e+01, gap 0.0%</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sim_mrs_space &lt;-<span class="st"> </span><span class="kw">update</span>(
    sim_ru,
    <span class="dt">amount.target=</span><span class="kw">c</span>(<span class="fl">0.2</span>,<span class="fl">0.2</span>,<span class="fl">0.2</span>),
    <span class="dt">space.target=</span><span class="kw">c</span>(<span class="fl">0.85</span>, <span class="fl">0.85</span>, <span class="fl">0.85</span>),
    <span class="dt">Threads=</span>threads
)</code></pre></div>
<pre><code>## Warning for adding variables: zero or small (&lt; 1e-13) coefficients, ignored
## Optimize a model with 30306 rows, 30100 columns and 120000 nonzeros
## Coefficient statistics:
##   Matrix range    [7e-03, 9e+01]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [1e+00, 1e+02]
## Found heuristic solution: objective 100
## Presolve removed 269 rows and 15 columns (presolve time = 5s) ...
## Presolve removed 360 rows and 15 columns
## Presolve time: 8.02s
## Presolved: 29946 rows, 30085 columns, 131504 nonzeros
## Variable types: 0 continuous, 30085 integer (30085 binary)
## Presolve removed 53 rows and 1 columns
## Presolved: 29893 rows, 30084 columns, 127236 nonzeros
## 
## Presolve removed 29893 rows and 30084 columns
## 
## Root simplex log...
## 
## Iteration    Objective       Primal Inf.    Dual Inf.      Time
##        0    1.0000000e+02   0.000000e+00   1.000000e+02      9s
##     4358    2.0000000e+01   0.000000e+00   0.000000e+00     10s
##     4358    2.0000000e+01   0.000000e+00   0.000000e+00     10s
## 
## Root relaxation: objective 2.000000e+01, 4358 iterations, 1.77 seconds
## Total elapsed time = 10.01s
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
## *    0     0               0      20.0000000   20.00000  0.00%     -   10s
## 
## Explored 0 nodes (6369 simplex iterations) in 10.13 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 2.000000000000e+01, best bound 2.000000000000e+01, gap 0.0%</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summaries</span>
<span class="kw">summary</span>(sim_mrs_amount)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL    20   20             20                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1              10               145               65
##   Connectivity_In_Fraction
## 1               0.04545455</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(sim_mrs_space)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL    20   20             20                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1               7               140               73
##   Connectivity_In_Fraction
## 1               0.03181818</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show amount held for each prioritisation</span>
<span class="kw">amount.held</span>(sim_mrs_amount)</code></pre></div>
<pre><code>##   uniform    normal   bimodal
## 1     0.2 0.2214677 0.2502513</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">amount.held</span>(sim_mrs_space)</code></pre></div>
<pre><code>##   uniform    normal   bimodal
## 1     0.2 0.2111175 0.2175549</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show space held for each prioritisation</span>
<span class="kw">space.held</span>(sim_mrs_amount)</code></pre></div>
<pre><code>##   uniform (Space 1) normal (Space 1) bimodal (Space 1)
## 1         0.9145455        0.8898895         0.9234012</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">space.held</span>(sim_mrs_space)</code></pre></div>
<pre><code>##   uniform (Space 1) normal (Space 1) bimodal (Space 1)
## 1         0.9333333        0.9111715          0.931071</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot multi-species prioritisation with amount-based targets</span>
<span class="kw">plot</span>(sim_mrs_amount, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Amount-based targets&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-33-1.png" title="_A multi-species prioritisation for the uniformly, normally, and bimodally distributed species generated using just amount-based targets (20\%). Squares represent planning units. Dark green planning units are selected for preservation._" alt="_A multi-species prioritisation for the uniformly, normally, and bimodally distributed species generated using just amount-based targets (20\%). Squares represent planning units. Dark green planning units are selected for preservation._" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot multi-species prioritisation with amount- and space-based targets</span>
<span class="kw">plot</span>(sim_mrs_space, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Amount and space-based targets&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-34-1.png" title="_A multi-species prioritisation for the uniformly, normally, and bimodally distributed species generated using amount-based targets (20\%) and space-based targets (85\%). See Figure 12 caption for conventions._" alt="_A multi-species prioritisation for the uniformly, normally, and bimodally distributed species generated using amount-based targets (20\%) and space-based targets (85\%). See Figure 12 caption for conventions._" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># difference between the two prioritisations</span>
<span class="kw">plot</span>(sim_mrs_amount, sim_mrs_space, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Difference between solutions&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-35-1.png" title="_Difference between two multi-species prioritisations. See Figure 7 caption for conventions.)" alt="_Difference between two multi-species prioritisations. See Figure 7 caption for conventions.)" style="display: block; margin: auto;" /></p>
<p>Here we can see that the inclusion of space-based targets changes which planning units are selected for prioritisation, but also the number of planning units that are selected. The amount-based prioritisation is comprised of 20 units, and the space-based prioritisation is comprised of 20 units. This result suggests that an adequate and representative prioritisation can be achieved for only a minor increase in cost.</p>
</div>
<div id="uncertainty-in-species-distributions" class="section level3">
<h3>Uncertainty in species’ distributions</h3>
<p>The unreliable formulation does not consider the probability that the planning units are occupied by features when calculating how well a given solution secures a representative sample of an attribute space. Thus solutions identified using the unreliable formulation may select regions of an attribute space for a species using planning units that only have a small chance of being inhabited. As a consequence, if the prioritisation is implemented, it may fail to secure regions of an attribute space if individuals do not inhabit these planning units, and ultimately fail to fulfil the space-based targets.</p>
<p>A simple solution to this issue would be to ensure that planning units cannot be assigned to demand points if they have a low probability of occupancy. This can be achieved by setting a probability threshold for planning units, such that planning units with a probability of occupancy below the threshold are effectively set to zero.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make new prioritisation with probability threshold of 0.1 for each species</span>
sim_mrs_space2 &lt;-<span class="st"> </span><span class="kw">solve</span>(
    <span class="kw">prob.subset</span>(
        sim_mrs_space,
        <span class="dt">species=</span><span class="dv">1</span>:<span class="dv">3</span>,
        <span class="dt">threshold=</span><span class="kw">c</span>(<span class="fl">0.1</span>,<span class="fl">0.1</span>,<span class="fl">0.1</span>)
    ),
    <span class="dt">Threads=</span>threads
)</code></pre></div>
<pre><code>## Warning for adding variables: zero or small (&lt; 1e-13) coefficients, ignored
## Optimize a model with 30306 rows, 30100 columns and 119974 nonzeros
## Coefficient statistics:
##   Matrix range    [7e-03, 9e+01]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [1e+00, 1e+02]
## Found heuristic solution: objective 100
## Presolve removed 271 rows and 15 columns (presolve time = 5s) ...
## Presolve removed 360 rows and 15 columns
## Presolve time: 7.99s
## Presolved: 29946 rows, 30085 columns, 131478 nonzeros
## Variable types: 0 continuous, 30085 integer (30085 binary)
## Presolve removed 53 rows and 1 columns
## Presolved: 29893 rows, 30084 columns, 127210 nonzeros
## 
## Presolve removed 29893 rows and 30084 columns
## 
## Root simplex log...
## 
## Iteration    Objective       Primal Inf.    Dual Inf.      Time
##        0    1.0000000e+02   0.000000e+00   1.000000e+02      9s
##     3717    2.0000000e+01   0.000000e+00   0.000000e+00     10s
##     3717    2.0000000e+01   0.000000e+00   0.000000e+00     10s
## 
## Root relaxation: objective 2.000000e+01, 3717 iterations, 1.96 seconds
## Total elapsed time = 10.00s
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
##      0     0   20.00000    0  216  100.00000   20.00000  80.0%     -   10s
## H    0     0                      22.0000000   20.00000  9.09%     -   10s
## 
## Explored 0 nodes (7281 simplex iterations) in 10.98 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 2.200000000000e+01, best bound 2.000000000000e+01, gap 9.0909%</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summary</span>
<span class="kw">summary</span>(sim_mrs_space2)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL    22   22             22                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1               8               134               78
##   Connectivity_In_Fraction
## 1               0.03636364</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot prioritisation</span>
<span class="kw">plot</span>(sim_mrs_space2, <span class="dv">1</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-38-1.png" title="_A multi-species prioritisation for the uniformly, normally, and bimodally distributed species generated using amount-based targets (20\%) and space-based targets (85\%). This priorititisation was generated to be robust against low occupancy probabilities, by preventing planning units with low probabilities from being used to represent demand points. See Figure 12 caption for conventions._" alt="_A multi-species prioritisation for the uniformly, normally, and bimodally distributed species generated using amount-based targets (20\%) and space-based targets (85\%). This priorititisation was generated to be robust against low occupancy probabilities, by preventing planning units with low probabilities from being used to represent demand points. See Figure 12 caption for conventions._" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># difference between prioritisations that use and do not use thresholds</span>
<span class="kw">plot</span>(sim_mrs_space2, sim_mrs_space, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Difference between solutions&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-39-1.png" title="_Difference between two multi-species prioritisations. See Figure 7 caption for conventions._" alt="_Difference between two multi-species prioritisations. See Figure 7 caption for conventions._" style="display: block; margin: auto;" /></p>
<p>But this method requires setting somewhat arbitrary thresholds. A more robust solution to this issue is to actually use the probability that species occupy planning units to generate the prioritisations. This is what the reliable formulation does. First we will try and generate a solution using existing targets and the reliable formulation. To reduce computational time, we will set the maximum backup <span class="math inline">\(R\)</span>-level to 1.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make new prioritisation using reliable formulation</span>
sim_mrs_space3 &lt;-<span class="st"> </span><span class="kw">try</span>(<span class="kw">update</span>(sim_mrs_space, <span class="dt">formulation=</span><span class="st">&#39;reliable&#39;</span>, <span class="dt">max.r.level=</span>1L, <span class="dt">Threads=</span>threads))</code></pre></div>
<pre><code>## Warning for adding variables: zero or small (&lt; 1e-13) coefficients, ignored
## Optimize a model with 364206 rows, 181900 columns and 3847200 nonzeros
## Coefficient statistics:
##   Matrix range    [8e-04, 1e+02]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [7e-03, 1e+02]
## Presolve removed 313400 rows and 65500 columns (presolve time = 5s) ...
## Presolve removed 338706 rows and 90806 columns
## Presolve time: 6.50s
## 
## Explored 0 nodes (0 simplex iterations) in 9.79 seconds
## Thread count was 1 (of 24 available processors)
## 
## Model is infeasible
## Best objective -, best bound -, gap -</code></pre>
<p>However, this fails. The reason why we cannot generate a prioritisation that fulfills these targets is because even the solution that contains all the planning units is still insufficient when we consider probabilities. The negative maximum targets printed in the error message indicate that planning units have low probabilities of occupancy. To fulfill the targets, we must obtain more planning units with higher probabilities of occupancy. We also could attempt resolving the problem using a higher <span class="math inline">\(R\)</span>-level. Instead, we will set lower targets and generate solution.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make new prioritisation using reliable formulation and reduced targets</span>
sim_mrs_space3 &lt;-<span class="st"> </span><span class="kw">update</span>(
    sim_mrs_space,
    <span class="dt">formulation=</span><span class="st">&#39;reliable&#39;</span>,
    <span class="dt">max.r.level=</span>1L,
    <span class="dt">space.target=</span>-<span class="dv">1000</span>,
    <span class="dt">Threads=</span>threads
)</code></pre></div>
<pre><code>## Warning for adding variables: zero or small (&lt; 1e-13) coefficients, ignored
## Optimize a model with 364206 rows, 181900 columns and 3847200 nonzeros
## Coefficient statistics:
##   Matrix range    [8e-04, 1e+02]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [7e-03, 8e+05]
## Presolve removed 333703 rows and 151600 columns (presolve time = 5s) ...
## Presolve removed 333903 rows and 151800 columns
## Presolve time: 7.50s
## Presolved: 30303 rows, 30100 columns, 90300 nonzeros
## Variable types: 0 continuous, 30100 integer (30100 binary)
## Found heuristic solution: objective 27.0000000
## Presolved: 30303 rows, 30100 columns, 90300 nonzeros
## 
## Presolve removed 30303 rows and 30100 columns
## 
## Root simplex log...
## 
## Iteration    Objective       Primal Inf.    Dual Inf.      Time
##        0    1.0000000e+02   0.000000e+00   1.000000e+02      9s
##      129    2.0000000e+01   0.000000e+00   0.000000e+00      9s
##      129    2.0000000e+01   0.000000e+00   0.000000e+00      9s
## 
## Root relaxation: objective 2.000000e+01, 129 iterations, 0.44 seconds
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
## *    0     0               0      20.0000000   20.00000  0.00%     -    9s
## 
## Explored 0 nodes (176 simplex iterations) in 9.56 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 2.000000000000e+01, best bound 2.000000000000e+01, gap 0.0%</code></pre>
<pre><code>## Warning in validityMethod(object): object@space.held contains values less
## than 0, some species are really poorly represented</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summary</span>
<span class="kw">summary</span>(sim_mrs_space3)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL    20   20             20                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1              21               157               42
##   Connectivity_In_Fraction
## 1               0.09545455</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot prioritisation</span>
<span class="kw">plot</span>(sim_mrs_space3, <span class="dv">1</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-43-1.png" title="_A multi-species prioritisation for the uniformly, normally, and bimodally distributed species generated using amount-based targets (20\%) and space-based targets (85\%). This priorititisation was generated to be robust against low occupancy probabilities, by explicitly using the probability of occupancy data when deriving a solution. See Figure 12 caption for conventions._" alt="_A multi-species prioritisation for the uniformly, normally, and bimodally distributed species generated using amount-based targets (20\%) and space-based targets (85\%). This priorititisation was generated to be robust against low occupancy probabilities, by explicitly using the probability of occupancy data when deriving a solution. See Figure 12 caption for conventions._" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># difference between prioritisations based on unreliable and reliable formulation</span>
<span class="kw">plot</span>(sim_mrs_space3, sim_mrs_space, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Difference between solutions&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-44-1.png" title="_Difference between two multi-species prioritisations. See Figure 7 caption for conventions._" alt="_Difference between two multi-species prioritisations. See Figure 7 caption for conventions._" style="display: block; margin: auto;" /></p>
<p>An additional planning unit was selected using the reliable formulation. The prioritisation based on the unreliable formulation had 20 planning units, but the prioritisation based on the reliable formlation has 20 planning units. This difference occurs because the reliable formulation needs to ensure that all selected planning units with a low chance of being occupied have a suitable backup planning unit. While the reliable formulation can deliver more robust prioritisations, it takes much longer to solve conservation planning problems expressed using this formulation than the unreliable formulation. As a consequence, the reliable formulation is only feasible for particularly small problems, such as those involving few features and less than several hundred planning units.</p>
</div>
<div id="fragmentation" class="section level3">
<h3>Fragmentation</h3>
<p>Fragmentation is an important consideration in real-world planning situations. Up until now, we haven’t considered the effects of fragmentation on the viability of the prioritisation. As a consequence, our prioritisations have tended to contain planning units without any neighbours. We can use the <code>BLM</code> parameter to penalise fragmented solutions.</p>
<p>Let’s generate a new prioritisation that heavily penalises fragmentation. Here, we will update the <code>sim_mrs_amount</code> object with <code>BLM</code> of 100.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># update prioritisation</span>
sim_mrs_amount_blm &lt;-<span class="st"> </span><span class="kw">update</span>(sim_mrs_amount, <span class="dt">BLM=</span><span class="dv">100</span>, <span class="dt">Threads=</span>threads)</code></pre></div>
<pre><code>## Warning for adding variables: zero or small (&lt; 1e-13) coefficients, ignored
## Optimize a model with 30666 rows, 30280 columns and 120720 nonzeros
## Coefficient statistics:
##   Matrix range    [7e-03, 9e+01]
##   Objective range [1e+02, 4e+02]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [1e+00, 8e+02]
## Found heuristic solution: objective 4498
## Presolve time: 1.35s
## Presolved: 30666 rows, 30280 columns, 120720 nonzeros
## Variable types: 0 continuous, 30280 integer (30280 binary)
## Presolved: 30666 rows, 30280 columns, 120720 nonzeros
## 
## Presolve removed 30666 rows and 30280 columns
## 
## Root simplex log...
## 
## Iteration    Objective       Primal Inf.    Dual Inf.      Time
##     5558    6.1282405e+02   0.000000e+00   9.029674e+05      5s
##     7593    4.6444444e+02   0.000000e+00   0.000000e+00      6s
##     7593    4.6444444e+02   0.000000e+00   0.000000e+00      7s
## 
## Root relaxation: objective 4.644444e+02, 7593 iterations, 5.13 seconds
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
##      0     0  464.44444    0 1725 4498.00000  464.44444  89.7%     -    6s
## H    0     0                    1531.0000000  464.44444  69.7%     -   20s
## H    0     0                    1122.0000000  464.44444  58.6%     -   21s
##      0     0  519.36948    0 1447 1122.00000  519.36948  53.7%     -   22s
##      0     0  519.36948    0 1451 1122.00000  519.36948  53.7%     -   24s
##      0     0  556.17021    0 1520 1122.00000  556.17021  50.4%     -   25s
##      0     0  556.17021    0 1527 1122.00000  556.17021  50.4%     -   25s
##      0     0  556.17021    0 1540 1122.00000  556.17021  50.4%     -   25s
##      0     0  556.17021    0 1542 1122.00000  556.17021  50.4%     -   26s
##      0     0  556.17021    0 1499 1122.00000  556.17021  50.4%     -   27s
##      0     0  556.17021    0 1500 1122.00000  556.17021  50.4%     -   29s
##      0     0  556.17021    0 1477 1122.00000  556.17021  50.4%     -   32s
##      0     0  556.17021    0 1480 1122.00000  556.17021  50.4%     -   35s
## H    0     0                    1120.0000000  556.17021  50.3%     -   35s
##      0     0  556.17021    0 1483 1120.00000  556.17021  50.3%     -   36s
##      0     0  556.17021    0 1481 1120.00000  556.17021  50.3%     -   36s
##      0     2  556.17021    0 1456 1120.00000  556.17021  50.3%     -   42s
##      9    13  612.82407    6 1387 1120.00000  586.72961  47.6%  1267   47s
##     33    47  632.55911   10 1090 1120.00000  612.02586  45.4%  1071   50s
##     95   109  693.30843   14 1217 1120.00000  625.08266  44.2%  1005   55s
##    303   264  834.28571   19  615 1120.00000  625.08266  44.2%   631   62s
##    458   391  960.00000   23  339 1120.00000  625.08266  44.2%   618   65s
##    584   484 1020.00000   34    2 1120.00000  637.61095  43.1%   621   71s
## H  649   436                    1020.0000000  637.61095  37.5%   559   71s
## H  821   350                     920.0000000  653.33333  29.0%   567   88s
##    906   309  833.88199   13 1026  920.00000  654.69388  28.8%   560   96s
##   1311   332  870.00000   20  985  920.00000  736.32265  20.0%   528  105s
##   1755   272     cutoff   20       920.00000  778.17223  15.4%   522  117s
##   2375    48     cutoff   25       920.00000  816.00000  11.3%   495  128s
## 
## Cutting planes:
##   Gomory: 2
##   Zero half: 206
## 
## Explored 3021 nodes (1421545 simplex iterations) in 128.52 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 9.200000000000e+02, best bound 8.520000000000e+02, gap 7.3913%</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summary of prioritisation</span>
<span class="kw">summary</span>(sim_mrs_amount_blm)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL   920   20             20                220
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1              31               171               18
##   Connectivity_In_Fraction
## 1                0.1409091</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show amount held for each prioritisation</span>
<span class="kw">amount.held</span>(sim_mrs_amount_blm)</code></pre></div>
<pre><code>##   uniform    normal   bimodal
## 1     0.2 0.3185057 0.3911267</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show space held for each prioritisation</span>
<span class="kw">space.held</span>(sim_mrs_amount_blm)</code></pre></div>
<pre><code>##   uniform (Space 1) normal (Space 1) bimodal (Space 1)
## 1               0.6        0.6277996         0.6899822</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot prioritisation</span>
<span class="kw">plot</span>(sim_mrs_amount_blm, <span class="dv">1</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-47-1.png" title="_A multi-species prioritisation for the uniformly, normally, and bimodally distributed species generated using only amount-based targets (20\%). Additionally, this priorititisation was specified to have high connectivity, by using a high $BLM$ parameter. See Figure 12 caption for conventions._" alt="_A multi-species prioritisation for the uniformly, normally, and bimodally distributed species generated using only amount-based targets (20\%). Additionally, this priorititisation was specified to have high connectivity, by using a high $BLM$ parameter. See Figure 12 caption for conventions._" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># difference between the two prioritisations</span>
<span class="kw">plot</span>(sim_mrs_amount_blm, sim_mrs_amount, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Difference between solutions&#39;</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-48-1.png" title="_Difference between two multi-species prioritisations. See Figure 7 caption for conventions._" alt="_Difference between two multi-species prioritisations. See Figure 7 caption for conventions._" style="display: block; margin: auto;" /></p>
<p>Here we can see that the prioritisation generated using a <code>BLM</code> parameter of 100 is much more clustered than the prioritisation generated using a <code>BLM</code> of 0. In practice, conservation planners will need to try a variety of <code>BLM</code> parameters to find a suitable prioritisation.</p>
</div>
</div>
</div>
<div id="case-study-examples" class="section level1">
<h1>Case-study examples</h1>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>Here we will investigate how space-based targets can affect prioritisations using a more realistic dataset. We will generate prioritisations for the four bird species–<a href="http://www.birdlife.org/datazone/speciesfactsheet.php?id=1092&amp;gclid=CjwKEAiApYGyBRC-g_jIstuduV8SJABCEzhZoONUy8VlwRZqeFB1Z5M03CjyneIvX8KdVKIPZvckrRoCgJDw_wcB">blue-winged kookaburra</a>, <a href="http://www.birdlife.org/datazone/species/factsheet/22704394?gclid=CjwKEAiApYGyBRC-g_jIstuduV8SJABCEzhZHxCTcR38YnFlhePYt19gD31lqxxwrMmtIuWFhUwLmRoCGJjw_wcB">brown-backed honeyeater</a>, <a href="http://www.birdlife.org/datazone/speciesfactsheet.php?id=3588">brown falcon</a>, <a href="http://www.birdlife.org/datazone/speciesfactsheet.php?id=1466">pale-headed rosella</a>–in Queensland, Australia. This region contains a broad range of different habitats–such as rainforests, woodlands, and deserts–making it ideal for this tutorial. First, we will generate a typical amount-based prioritisation that aims to capture 20% of the species’ distributions. Then we will generate a prioritisation that also aims to secure populations in representative parts of the species’ distributions in terms of their geographic location and their environmental heterogeneity. To do this we will generate a prioritisation using 20% amount-based targets and 85% space-based targets. Finally, we will compare these prioritisations to Australia’s existing protected network.</p>
</div>
<div id="data-1" class="section level2">
<h2>Data</h2>
<p>To map the coarse-scale distributions of the four bird species, we obtained observation data from the Atlas of Living Australia across the whole of Australia [using the  package], spatially thinned the data to omit points within 10,000 km<span class="math inline">\(^2\)</span> of each other to ameliorate the effects of sampling bias [using the developmental version of the  package; ], and fit 85 % minimum convex polygons [using the  package]. We used this method because it is entirely reproducible using freely available data. The code used to generate this maps is available in the <a href="https://github.com/jeffreyhanson/raptr-manuscript">GitHub repository for the scientific article accompanying this R package</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load data</span>
<span class="kw">data</span>(cs_spp)

<span class="co"># plot species&#39; distributions</span>
<span class="kw">plot</span>(cs_spp, <span class="dt">main=</span><span class="kw">c</span>(
    <span class="st">&quot;Blue-winged kookaburra&quot;</span>, <span class="st">&quot;Brown-backed honeyeater&quot;</span>, 
    <span class="st">&quot;Brown falcon&quot;</span>, <span class="st">&quot;Pale-headed rosella&quot;</span>
))</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-49-1.png" title="_Distribution map for four Australian bird species. ._" alt="_Distribution map for four Australian bird species. ._" style="display: block; margin: auto;" /></p>
<p>Planning units (50km<span class="math inline">\(^2\)</span> resolution) were generated across Australia, and then clipped to the <a href="http://www.abs.gov.au/ausstats/abs@.nsf/mf/1259.0.30.001?OpenDocument">Queensland state borders and coastline</a>. <strong>Note that we are using excessively coarse planning units so that our examples will complete relatively quickly. In a real-world planning exercise, we would use much finer planning units.</strong> To compare our prioritisations to <a href="http://www.protectedplanet.net/country/AU">Queensland’s existing protected area network</a>, this network was intersected with the planning units. Planning units with more than 50% of their area inside a protected area had their status set to 2 (<a href="http://marxan.net/downloads/uq_marxan_web_2/module4.html">following conventions in <em>Marxan</em></a>). Since we do not have cost data, the prioritisations will aim to select the minimum number of planning units required to meet the targets. The planning units are stored in the <code>cs_pu</code> object.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load data</span>
<span class="kw">data</span>(cs_pus)

## plot planning units
<span class="co"># convert SpatialPolygons to PolySet for quick plotting</span>
cs_pus2 &lt;-<span class="st"> </span><span class="kw">SpatialPolygons2PolySet</span>(cs_pus)

<span class="co"># create vector of colours for planning units</span>
<span class="co"># + light green: units not already inside reserve</span>
<span class="co"># + yellow: units already inside reserve</span>
cs_pus_cols &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="st">&#39;#c7e9c0&#39;</span>, <span class="kw">nrow</span>(cs_pus@data))
cs_pus_cols[<span class="kw">which</span>(cs_pus$status==<span class="dv">2</span>)] &lt;-<span class="st"> &#39;yellow&#39;</span>

<span class="co"># set plotting window</span>
<span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">4.1</span>, <span class="fl">0.1</span>))

<span class="co"># plot polygons</span>
PBSmapping::<span class="kw">plotPolys</span>(
    cs_pus2, <span class="dt">col=</span>cs_pus_cols, <span class="dt">border=</span><span class="st">&#39;gray30&#39;</span>, 
    <span class="dt">xlab=</span><span class="st">&#39;&#39;</span>, <span class="dt">ylab=</span><span class="st">&#39;&#39;</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>, 
    <span class="dt">main=</span><span class="st">&#39;Case-study planning units&#39;</span>,
    <span class="dt">cex=</span><span class="fl">1.8</span>
)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-50-1.png" title="_Planning units for the case-study examples. Polygons denote planning units. Yellow units have more than 50\% of their area already in a reserve.)" alt="_Planning units for the case-study examples. Polygons denote planning units. Yellow units have more than 50\% of their area already in a reserve.)" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># reset plotting window</span>
<span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">5.1</span>, <span class="fl">4.1</span>, <span class="fl">4.1</span>, <span class="fl">2.1</span>))</code></pre></div>
<p>To map the distribution of environmental conditions across the species’ range, 21 <a href="http://www.worldclim.org/bioclim">bioclimatic layers</a> were obtained. These layers were cropped to Australia and subject to <a href="http://cc.oulu.fi/~jarioksa/softhelp/vegan/html/decorana.html">detrended correspondence analysis</a> to produce two new variables. These layers are stored in the <code>cs_space</code> object.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load data</span>
<span class="kw">data</span>(cs_space)

<span class="co"># plot variables</span>
<span class="kw">plot</span>(cs_space, <span class="dt">main=</span><span class="kw">c</span>(<span class="st">&#39;DC1&#39;</span>, <span class="st">&#39;DC2&#39;</span>), <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-51-1.png" title="_Broad-scale environmental variation across Australia. The variable DC1 describes the transition from wet and cool to dry and hot conditions. The variable DC2 describes the transition from wet and hot to dry and cool conditions._" alt="_Broad-scale environmental variation across Australia. The variable DC1 describes the transition from wet and cool to dry and hot conditions. The variable DC2 describes the transition from wet and hot to dry and cool conditions._" style="display: block; margin: auto;" /></p>
</div>
<div id="analysis" class="section level2">
<h2>Analysis</h2>
<p>To simplify the process of formatting data and generating prioritisations, we can use the <code>rap</code> function. First, we will generate an amount-based prioritisation that aims to capture 10% of the rosella’s range. We will use 50 demand points to map the geographic and environmental spaces. <strong>Be warned, the examples hereafter can take 5-10 minutes to run.</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make amount-based prioritisation</span>
<span class="co"># and ignore existing protected areas by discarding values in the </span>
<span class="co"># status (third) column of the attribute table</span>
cs_rs_amount &lt;-<span class="st"> </span><span class="kw">rap</span>(
    cs_pus[,-<span class="dv">2</span>], cs_spp, cs_space,
    <span class="dt">amount.target=</span><span class="fl">0.2</span>, <span class="dt">space.target=</span><span class="ot">NA</span>, <span class="dt">n.demand.points=</span>50L,
    <span class="dt">include.geographic.space=</span><span class="ot">TRUE</span>, <span class="dt">formulation=</span><span class="st">&#39;unreliable&#39;</span>,
    <span class="dt">kernel.method=</span><span class="st">&#39;hypervolume&#39;</span>, <span class="dt">quantile=</span><span class="fl">0.7</span>, <span class="dt">solve=</span><span class="ot">FALSE</span>
)</code></pre></div>
<pre><code>## Warning in (function (pus, species, spaces = NULL, amount.target = 0.2, :
## argument to pus does not have a &#39;status&#39; column, creating default with all
## status=0L</code></pre>
<pre><code>## Evaluating probability density...
## Building tree... done.
## Querying tree... 6.97837e-07  0.00697906  0.0139574  0.0209358  0.0279142  0.0348925  0.0418709  0.0488493  0.0558276  0.062806  0.0697844  0.0767627  0.0837411  0.0907195  0.0976978  0.104676  0.111655  0.118633  0.125611  0.13259  0.139568  0.146546  0.153525  0.160503  0.167482  0.17446  0.181438  0.188417  0.195395  0.202373  0.209352  0.21633  0.223308  0.230287  0.237265  0.244244  0.251222  0.2582  0.265179  0.272157  0.279135  0.286114  0.293092  0.30007  0.307049  0.314027  0.321006  0.327984  0.334962  0.341941  0.348919  0.355897  0.362876  0.369854  0.376833  0.383811  0.390789  0.397768  0.404746  0.411724  0.418703  0.425681  0.432659  0.439638  0.446616  0.453595  0.460573  0.467551  0.47453  0.481508  0.488486  0.495465  0.502443  0.509421  0.5164  0.523378  0.530357  0.537335  0.544313  0.551292  0.55827  0.565248  0.572227  0.579205  0.586184  0.593162  0.60014  0.607119  0.614097  0.621075  0.628054  0.635032  0.64201  0.648989  0.655967  0.662946  0.669924  0.676902  0.683881  0.690859  0.697837  0.704816  0.711794  0.718773  0.725751  0.732729  0.739708  0.746686  0.753664  0.760643  0.767621  0.774599  0.781578  0.788556  0.795535  0.802513  0.809491  0.81647  0.823448  0.830426  0.837405  0.844383  0.851361  0.85834  0.865318  0.872297  0.879275  0.886253  0.893232  0.90021  0.907188  0.914167  0.921145  0.928124  0.935102  0.94208  0.949059  0.956037  0.963015  0.969994  0.976972  0.98395  0.990929  0.997907  done.
## Finished evaluating probability density.
## Beginning volume calculation... done. 
## Quantile requested: 0.70   obtained: 0.70
## Evaluating probability density...
## Building tree... done.
## Querying tree... 5.20833e-06  0.0520885  0.104172  0.156255  0.208339  0.260422  0.312505  0.364589  0.416672  0.468755  0.520839  0.572922  0.625005  0.677089  0.729172  0.781255  0.833339  0.885422  0.937505  0.989589  done.
## Finished evaluating probability density.
## Beginning volume calculation... done. 
## Quantile requested: 0.70   obtained: 0.69
## Evaluating probability density...
## Building tree... done.
## Querying tree... 2.59808e-07  0.00259834  0.00519641  0.00779449  0.0103926  0.0129906  0.0155887  0.0181868  0.0207849  0.023383  0.025981  0.0285791  0.0311772  0.0337753  0.0363733  0.0389714  0.0415695  0.0441676  0.0467657  0.0493637  0.0519618  0.0545599  0.057158  0.059756  0.0623541  0.0649522  0.0675503  0.0701484  0.0727464  0.0753445  0.0779426  0.0805407  0.0831387  0.0857368  0.0883349  0.090933  0.093531  0.0961291  0.0987272  0.101325  0.103923  0.106521  0.10912  0.111718  0.114316  0.116914  0.119512  0.12211  0.124708  0.127306  0.129904  0.132502  0.1351  0.137698  0.140296  0.142895  0.145493  0.148091  0.150689  0.153287  0.155885  0.158483  0.161081  0.163679  0.166277  0.168875  0.171473  0.174071  0.17667  0.179268  0.181866  0.184464  0.187062  0.18966  0.192258  0.194856  0.197454  0.200052  0.20265  0.205248  0.207846  0.210445  0.213043  0.215641  0.218239  0.220837  0.223435  0.226033  0.228631  0.231229  0.233827  0.236425  0.239023  0.241621  0.24422  0.246818  0.249416  0.252014  0.254612  0.25721  0.259808  0.262406  0.265004  0.267602  0.2702  0.272798  0.275396  0.277995  0.280593  0.283191  0.285789  0.288387  0.290985  0.293583  0.296181  0.298779  0.301377  0.303975  0.306573  0.309171  0.31177  0.314368  0.316966  0.319564  0.322162  0.32476  0.327358  0.329956  0.332554  0.335152  0.33775  0.340348  0.342946  0.345545  0.348143  0.350741  0.353339  0.355937  0.358535  0.361133  0.363731  0.366329  0.368927  0.371525  0.374123  0.376721  0.37932  0.381918  0.384516  0.387114  0.389712  0.39231  0.394908  0.397506  0.400104  0.402702  0.4053  0.407898  0.410496  0.413095  0.415693  0.418291  0.420889  0.423487  0.426085  0.428683  0.431281  0.433879  0.436477  0.439075  0.441673  0.444271  0.44687  0.449468  0.452066  0.454664  0.457262  0.45986  0.462458  0.465056  0.467654  0.470252  0.47285  0.475448  0.478047  0.480645  0.483243  0.485841  0.488439  0.491037  0.493635  0.496233  0.498831  0.501429  0.504027  0.506625  0.509223  0.511822  0.51442  0.517018  0.519616  0.522214  0.524812  0.52741  0.530008  0.532606  0.535204  0.537802  0.5404  0.542998  0.545597  0.548195  0.550793  0.553391  0.555989  0.558587  0.561185  0.563783  0.566381  0.568979  0.571577  0.574175  0.576773  0.579372  0.58197  0.584568  0.587166  0.589764  0.592362  0.59496  0.597558  0.600156  0.602754  0.605352  0.60795  0.610548  0.613147  0.615745  0.618343  0.620941  0.623539  0.626137  0.628735  0.631333  0.633931  0.636529  0.639127  0.641725  0.644323  0.646922  0.64952  0.652118  0.654716  0.657314  0.659912  0.66251  0.665108  0.667706  0.670304  0.672902  0.6755  0.678098  0.680697  0.683295  0.685893  0.688491  0.691089  0.693687  0.696285  0.698883  0.701481  0.704079  0.706677  0.709275  0.711873  0.714472  0.71707  0.719668  0.722266  0.724864  0.727462  0.73006  0.732658  0.735256  0.737854  0.740452  0.74305  0.745648  0.748247  0.750845  0.753443  0.756041  0.758639  0.761237  0.763835  0.766433  0.769031  0.771629  0.774227  0.776825  0.779423  0.782022  0.78462  0.787218  0.789816  0.792414  0.795012  0.79761  0.800208  0.802806  0.805404  0.808002  0.8106  0.813198  0.815797  0.818395  0.820993  0.823591  0.826189  0.828787  0.831385  0.833983  0.836581  0.839179  0.841777  0.844375  0.846973  0.849572  0.85217  0.854768  0.857366  0.859964  0.862562  0.86516  0.867758  0.870356  0.872954  0.875552  0.87815  0.880749  0.883347  0.885945  0.888543  0.891141  0.893739  0.896337  0.898935  0.901533  0.904131  0.906729  0.909327  0.911925  0.914524  0.917122  0.91972  0.922318  0.924916  0.927514  0.930112  0.93271  0.935308  0.937906  0.940504  0.943102  0.9457  0.948299  0.950897  0.953495  0.956093  0.958691  0.961289  0.963887  0.966485  0.969083  0.971681  0.974279  0.976877  0.979475  0.982074  0.984672  0.98727  0.989868  0.992466  0.995064  0.997662  done.
## Finished evaluating probability density.
## Beginning volume calculation... done. 
## Quantile requested: 0.70   obtained: 0.70
## Evaluating probability density...
## Building tree... done.
## Querying tree... 7.3692e-07  0.00736993  0.0147391  0.0221083  0.0294775  0.0368467  0.0442159  0.0515851  0.0589543  0.0663235  0.0736927  0.0810619  0.0884311  0.0958003  0.103169  0.110539  0.117908  0.125277  0.132646  0.140015  0.147385  0.154754  0.162123  0.169492  0.176861  0.184231  0.1916  0.198969  0.206338  0.213707  0.221077  0.228446  0.235815  0.243184  0.250553  0.257923  0.265292  0.272661  0.28003  0.287399  0.294769  0.302138  0.309507  0.316876  0.324245  0.331615  0.338984  0.346353  0.353722  0.361091  0.368461  0.37583  0.383199  0.390568  0.397937  0.405307  0.412676  0.420045  0.427414  0.434783  0.442153  0.449522  0.456891  0.46426  0.471629  0.478999  0.486368  0.493737  0.501106  0.508475  0.515845  0.523214  0.530583  0.537952  0.545321  0.55269  0.56006  0.567429  0.574798  0.582167  0.589536  0.596906  0.604275  0.611644  0.619013  0.626382  0.633752  0.641121  0.64849  0.655859  0.663228  0.670598  0.677967  0.685336  0.692705  0.700074  0.707444  0.714813  0.722182  0.729551  0.73692  0.74429  0.751659  0.759028  0.766397  0.773766  0.781136  0.788505  0.795874  0.803243  0.810612  0.817982  0.825351  0.83272  0.840089  0.847458  0.854828  0.862197  0.869566  0.876935  0.884304  0.891674  0.899043  0.906412  0.913781  0.92115  0.92852  0.935889  0.943258  0.950627  0.957996  0.965366  0.972735  0.980104  0.987473  0.994842  done.
## Finished evaluating probability density.
## Beginning volume calculation... done. 
## Quantile requested: 0.70   obtained: 0.70
## Evaluating probability density...
## Building tree... done.
## Querying tree... 6.97837e-07  0.00697906  0.0139574  0.0209358  0.0279142  0.0348925  0.0418709  0.0488493  0.0558276  0.062806  0.0697844  0.0767627  0.0837411  0.0907195  0.0976978  0.104676  0.111655  0.118633  0.125611  0.13259  0.139568  0.146546  0.153525  0.160503  0.167482  0.17446  0.181438  0.188417  0.195395  0.202373  0.209352  0.21633  0.223308  0.230287  0.237265  0.244244  0.251222  0.2582  0.265179  0.272157  0.279135  0.286114  0.293092  0.30007  0.307049  0.314027  0.321006  0.327984  0.334962  0.341941  0.348919  0.355897  0.362876  0.369854  0.376833  0.383811  0.390789  0.397768  0.404746  0.411724  0.418703  0.425681  0.432659  0.439638  0.446616  0.453595  0.460573  0.467551  0.47453  0.481508  0.488486  0.495465  0.502443  0.509421  0.5164  0.523378  0.530357  0.537335  0.544313  0.551292  0.55827  0.565248  0.572227  0.579205  0.586184  0.593162  0.60014  0.607119  0.614097  0.621075  0.628054  0.635032  0.64201  0.648989  0.655967  0.662946  0.669924  0.676902  0.683881  0.690859  0.697837  0.704816  0.711794  0.718773  0.725751  0.732729  0.739708  0.746686  0.753664  0.760643  0.767621  0.774599  0.781578  0.788556  0.795535  0.802513  0.809491  0.81647  0.823448  0.830426  0.837405  0.844383  0.851361  0.85834  0.865318  0.872297  0.879275  0.886253  0.893232  0.90021  0.907188  0.914167  0.921145  0.928124  0.935102  0.94208  0.949059  0.956037  0.963015  0.969994  0.976972  0.98395  0.990929  0.997907  done.
## Finished evaluating probability density.
## Beginning volume calculation... done. 
## Quantile requested: 0.70   obtained: 0.70</code></pre>
<pre><code>## Warning in (function (data, repsperpoint = NULL, bandwidth, quantile = 0, : 
##  Dimensions x and y are highly correlated (r=-0.85)
## Consider removing some axes.</code></pre>
<pre><code>## Evaluating probability density...
## Building tree... done.
## Querying tree... 5.20833e-06  0.0520885  0.104172  0.156255  0.208339  0.260422  0.312505  0.364589  0.416672  0.468755  0.520839  0.572922  0.625005  0.677089  0.729172  0.781255  0.833339  0.885422  0.937505  0.989589  done.
## Finished evaluating probability density.
## Beginning volume calculation... done. 
## Quantile requested: 0.70   obtained: 0.70
## Evaluating probability density...
## Building tree... done.
## Querying tree... 2.59808e-07  0.00259834  0.00519641  0.00779449  0.0103926  0.0129906  0.0155887  0.0181868  0.0207849  0.023383  0.025981  0.0285791  0.0311772  0.0337753  0.0363733  0.0389714  0.0415695  0.0441676  0.0467657  0.0493637  0.0519618  0.0545599  0.057158  0.059756  0.0623541  0.0649522  0.0675503  0.0701484  0.0727464  0.0753445  0.0779426  0.0805407  0.0831387  0.0857368  0.0883349  0.090933  0.093531  0.0961291  0.0987272  0.101325  0.103923  0.106521  0.10912  0.111718  0.114316  0.116914  0.119512  0.12211  0.124708  0.127306  0.129904  0.132502  0.1351  0.137698  0.140296  0.142895  0.145493  0.148091  0.150689  0.153287  0.155885  0.158483  0.161081  0.163679  0.166277  0.168875  0.171473  0.174071  0.17667  0.179268  0.181866  0.184464  0.187062  0.18966  0.192258  0.194856  0.197454  0.200052  0.20265  0.205248  0.207846  0.210445  0.213043  0.215641  0.218239  0.220837  0.223435  0.226033  0.228631  0.231229  0.233827  0.236425  0.239023  0.241621  0.24422  0.246818  0.249416  0.252014  0.254612  0.25721  0.259808  0.262406  0.265004  0.267602  0.2702  0.272798  0.275396  0.277995  0.280593  0.283191  0.285789  0.288387  0.290985  0.293583  0.296181  0.298779  0.301377  0.303975  0.306573  0.309171  0.31177  0.314368  0.316966  0.319564  0.322162  0.32476  0.327358  0.329956  0.332554  0.335152  0.33775  0.340348  0.342946  0.345545  0.348143  0.350741  0.353339  0.355937  0.358535  0.361133  0.363731  0.366329  0.368927  0.371525  0.374123  0.376721  0.37932  0.381918  0.384516  0.387114  0.389712  0.39231  0.394908  0.397506  0.400104  0.402702  0.4053  0.407898  0.410496  0.413095  0.415693  0.418291  0.420889  0.423487  0.426085  0.428683  0.431281  0.433879  0.436477  0.439075  0.441673  0.444271  0.44687  0.449468  0.452066  0.454664  0.457262  0.45986  0.462458  0.465056  0.467654  0.470252  0.47285  0.475448  0.478047  0.480645  0.483243  0.485841  0.488439  0.491037  0.493635  0.496233  0.498831  0.501429  0.504027  0.506625  0.509223  0.511822  0.51442  0.517018  0.519616  0.522214  0.524812  0.52741  0.530008  0.532606  0.535204  0.537802  0.5404  0.542998  0.545597  0.548195  0.550793  0.553391  0.555989  0.558587  0.561185  0.563783  0.566381  0.568979  0.571577  0.574175  0.576773  0.579372  0.58197  0.584568  0.587166  0.589764  0.592362  0.59496  0.597558  0.600156  0.602754  0.605352  0.60795  0.610548  0.613147  0.615745  0.618343  0.620941  0.623539  0.626137  0.628735  0.631333  0.633931  0.636529  0.639127  0.641725  0.644323  0.646922  0.64952  0.652118  0.654716  0.657314  0.659912  0.66251  0.665108  0.667706  0.670304  0.672902  0.6755  0.678098  0.680697  0.683295  0.685893  0.688491  0.691089  0.693687  0.696285  0.698883  0.701481  0.704079  0.706677  0.709275  0.711873  0.714472  0.71707  0.719668  0.722266  0.724864  0.727462  0.73006  0.732658  0.735256  0.737854  0.740452  0.74305  0.745648  0.748247  0.750845  0.753443  0.756041  0.758639  0.761237  0.763835  0.766433  0.769031  0.771629  0.774227  0.776825  0.779423  0.782022  0.78462  0.787218  0.789816  0.792414  0.795012  0.79761  0.800208  0.802806  0.805404  0.808002  0.8106  0.813198  0.815797  0.818395  0.820993  0.823591  0.826189  0.828787  0.831385  0.833983  0.836581  0.839179  0.841777  0.844375  0.846973  0.849572  0.85217  0.854768  0.857366  0.859964  0.862562  0.86516  0.867758  0.870356  0.872954  0.875552  0.87815  0.880749  0.883347  0.885945  0.888543  0.891141  0.893739  0.896337  0.898935  0.901533  0.904131  0.906729  0.909327  0.911925  0.914524  0.917122  0.91972  0.922318  0.924916  0.927514  0.930112  0.93271  0.935308  0.937906  0.940504  0.943102  0.9457  0.948299  0.950897  0.953495  0.956093  0.958691  0.961289  0.963887  0.966485  0.969083  0.971681  0.974279  0.976877  0.979475  0.982074  0.984672  0.98727  0.989868  0.992466  0.995064  0.997662  done.
## Finished evaluating probability density.
## Beginning volume calculation... done. 
## Quantile requested: 0.70   obtained: 0.69
## Evaluating probability density...
## Building tree... done.
## Querying tree... 7.3692e-07  0.00736993  0.0147391  0.0221083  0.0294775  0.0368467  0.0442159  0.0515851  0.0589543  0.0663235  0.0736927  0.0810619  0.0884311  0.0958003  0.103169  0.110539  0.117908  0.125277  0.132646  0.140015  0.147385  0.154754  0.162123  0.169492  0.176861  0.184231  0.1916  0.198969  0.206338  0.213707  0.221077  0.228446  0.235815  0.243184  0.250553  0.257923  0.265292  0.272661  0.28003  0.287399  0.294769  0.302138  0.309507  0.316876  0.324245  0.331615  0.338984  0.346353  0.353722  0.361091  0.368461  0.37583  0.383199  0.390568  0.397937  0.405307  0.412676  0.420045  0.427414  0.434783  0.442153  0.449522  0.456891  0.46426  0.471629  0.478999  0.486368  0.493737  0.501106  0.508475  0.515845  0.523214  0.530583  0.537952  0.545321  0.55269  0.56006  0.567429  0.574798  0.582167  0.589536  0.596906  0.604275  0.611644  0.619013  0.626382  0.633752  0.641121  0.64849  0.655859  0.663228  0.670598  0.677967  0.685336  0.692705  0.700074  0.707444  0.714813  0.722182  0.729551  0.73692  0.74429  0.751659  0.759028  0.766397  0.773766  0.781136  0.788505  0.795874  0.803243  0.810612  0.817982  0.825351  0.83272  0.840089  0.847458  0.854828  0.862197  0.869566  0.876935  0.884304  0.891674  0.899043  0.906412  0.913781  0.92115  0.92852  0.935889  0.943258  0.950627  0.957996  0.965366  0.972735  0.980104  0.987473  0.994842  done.
## Finished evaluating probability density.
## Beginning volume calculation... done. 
## Quantile requested: 0.70   obtained: 0.69</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># generate prioritisation</span>
cs_rs_amount &lt;-<span class="st"> </span><span class="kw">solve</span>(cs_rs_amount, <span class="dt">MIPGap=</span><span class="fl">0.1</span>, <span class="dt">Threads=</span>threads)</code></pre></div>
<pre><code>## Optimize a model with 4 rows, 762 columns and 2267 nonzeros
## Coefficient statistics:
##   Matrix range    [2e+02, 2e+04]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [2e+05, 3e+06]
## Found heuristic solution: objective 158
## Presolve time: 0.01s
## Presolved: 4 rows, 762 columns, 2267 nonzeros
## Variable types: 0 continuous, 762 integer (762 binary)
## Presolved: 4 rows, 762 columns, 2267 nonzeros
## 
## 
## Root relaxation: objective 1.359395e+02, 865 iterations, 0.00 seconds
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
##      0     0  135.93952    0    4  158.00000  135.93952  14.0%     -    0s
## H    0     0                     136.0000000  135.93952  0.04%     -    0s
## 
## Explored 0 nodes (865 simplex iterations) in 0.02 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 1.360000000000e+02, best bound 1.360000000000e+02, gap 0.0%</code></pre>
<pre><code>## Warning in validityMethod(object): object@space.held contains values less
## than 0, some species are really poorly represented</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summary</span>
<span class="kw">summary</span>(cs_rs_amount)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL   136  136            136           98882414
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1         9686021          81170163          8026230
##   Connectivity_In_Fraction
## 1               0.09795494</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot prioritisation</span>
<span class="kw">plot</span>(cs_rs_amount, <span class="dv">1</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-54-1.png" title="_Multi-species prioritisation generated for four bird species using amount-based targets (20\%). See Figure 12 captions for conventions._" alt="_Multi-species prioritisation generated for four bird species using amount-based targets (20\%). See Figure 12 captions for conventions._" style="display: block; margin: auto;" /></p>
<p>We can also see how well the prioritisation secures the species’ distributions in the geographic and environmental attribute spaces.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot prioritisation in geographic attribute space</span>
p1 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_amount, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dt">main=</span><span class="st">&#39;Blue-winged</span><span class="ch">\n</span><span class="st">kookaburra&#39;</span>)
p2 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_amount, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dt">main=</span><span class="st">&#39;Brown-backed</span><span class="ch">\n</span><span class="st">honeyeater&#39;</span>)
p3 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_amount, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dt">main=</span><span class="st">&#39;Brown falcon&#39;</span>)
p4 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_amount, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dt">main=</span><span class="st">&#39;Pale-headed</span><span class="ch">\n</span><span class="st">rosella&#39;</span>)
gridExtra::<span class="kw">grid.arrange</span>(p1, p2, p3, p4, <span class="dt">ncol=</span><span class="dv">2</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-55-1.png" title="_Distribution of amount-based prioritisation in the geographic attribute space. Points denote combinations of environmental conditions. Green and grey points represent planning unit selected for and not selected for prioritisation (respectively). Blue points denote demand points, and their size indicates their weighting._" alt="_Distribution of amount-based prioritisation in the geographic attribute space. Points denote combinations of environmental conditions. Green and grey points represent planning unit selected for and not selected for prioritisation (respectively). Blue points denote demand points, and their size indicates their weighting._" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot prioritisation in environmental attribute space</span>
p1 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_amount, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Blue-winged</span><span class="ch">\n</span><span class="st">kookaburra&#39;</span>)
p2 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_amount, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Brown-backed</span><span class="ch">\n</span><span class="st">honeyeater&#39;</span>)
p3 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_amount, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Brown falcon&#39;</span>)
p4 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_amount, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Pale-headed</span><span class="ch">\n</span><span class="st">rosella&#39;</span>)
gridExtra::<span class="kw">grid.arrange</span>(p1, p2, p3, p4, <span class="dt">ncol=</span><span class="dv">2</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-56-1.png" title="_Distribution of amount-based prioritisation in the environmental attribute space. See Figure 28 caption for conventions._" alt="_Distribution of amount-based prioritisation in the environmental attribute space. See Figure 28 caption for conventions._" style="display: block; margin: auto;" /></p>
<p>Next, let’s generate a prioritisation using amount- and space-based targets. This prioritisation will secure 70% of the species distribution in geographic and environmental space.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make amount- and space-based prioritisation</span>
cs_rs_space &lt;-<span class="st"> </span><span class="kw">update</span>(cs_rs_amount, <span class="dt">space.target=</span><span class="fl">0.7</span>, <span class="dt">Threads=</span>threads)</code></pre></div>
<pre><code>## Optimize a model with 227112 rows, 227462 columns and 909067 nonzeros
## Coefficient statistics:
##   Matrix range    [3e-04, 2e+04]
##   Objective range [1e+00, 1e+00]
##   Bounds range    [1e+00, 1e+00]
##   RHS range       [1e+00, 3e+06]
## Presolve removed 2750 rows and 2692 columns (presolve time = 5s) ...
## Presolve removed 3265 rows and 2692 columns (presolve time = 10s) ...
## Presolve removed 3884 rows and 2692 columns (presolve time = 15s) ...
## Presolve removed 4640 rows and 2692 columns (presolve time = 20s) ...
## Presolve removed 4982 rows and 2692 columns (presolve time = 25s) ...
## Presolve removed 4994 rows and 2692 columns (presolve time = 30s) ...
## Presolve removed 5006 rows and 2692 columns (presolve time = 35s) ...
## Presolve removed 5028 rows and 2692 columns (presolve time = 40s) ...
## Presolve removed 5034 rows and 2692 columns (presolve time = 45s) ...
## Presolve removed 5406 rows and 2692 columns (presolve time = 50s) ...
## Presolve removed 6644 rows and 2692 columns (presolve time = 55s) ...
## Presolve removed 6917 rows and 2692 columns (presolve time = 60s) ...
## Presolve removed 6917 rows and 2692 columns (presolve time = 65s) ...
## Presolve removed 6994 rows and 2692 columns (presolve time = 70s) ...
## Presolve removed 7210 rows and 2692 columns (presolve time = 75s) ...
## Presolve removed 7474 rows and 2692 columns (presolve time = 80s) ...
## Presolve removed 7475 rows and 2692 columns (presolve time = 85s) ...
## Presolve removed 7496 rows and 2692 columns (presolve time = 90s) ...
## Presolve removed 7496 rows and 2692 columns (presolve time = 95s) ...
## Presolve removed 7678 rows and 2692 columns (presolve time = 100s) ...
## Presolve removed 7678 rows and 2692 columns (presolve time = 134s) ...
## Presolve removed 7678 rows and 2692 columns
## Presolve time: 133.90s
## Presolved: 219434 rows, 224770 columns, 967033 nonzeros
## Variable types: 0 continuous, 224770 integer (224770 binary)
## Found heuristic solution: objective 272.0000000
## Presolve removed 1556 rows and 0 columns (presolve time = 5s) ...
## Presolve removed 1556 rows and 0 columns (presolve time = 10s) ...
## Presolve removed 1556 rows and 0 columns
## Presolved: 217878 rows, 224770 columns, 962255 nonzeros
## 
## Presolve removed 217878 rows and 224770 columns
## 
## Root simplex log...
## 
## Iteration    Objective       Primal Inf.    Dual Inf.      Time
##        0    7.6200000e+02   0.000000e+00   7.620000e+02    147s
##     7999    1.3835432e+02   0.000000e+00   7.408546e+03    150s
##    16095    1.3649366e+02   0.000000e+00   2.921838e+03    155s
##    22420    1.3624141e+02   0.000000e+00   9.459410e+02    160s
##    28492    1.3616854e+02   0.000000e+00   5.588955e+02    165s
##    32793    1.3610801e+02   0.000000e+00   7.126031e+02    170s
##    36588    1.3608115e+02   0.000000e+00   1.065871e+03    175s
##    39624    1.3604632e+02   0.000000e+00   3.909588e+02    180s
##    45190    1.3601633e+02   0.000000e+00   1.341413e+02    185s
##    48985    1.3601066e+02   0.000000e+00   5.022738e+01    190s
##    53033    1.3599177e+02   0.000000e+00   8.299664e+01    195s
##    57587    1.3597076e+02   0.000000e+00   3.371841e+01    200s
##    62647    1.3596338e+02   0.000000e+00   4.236870e+01    205s
##    66695    1.3595770e+02   0.000000e+00   2.309907e-01    211s
##    67018    1.3595610e+02   0.000000e+00   0.000000e+00    212s
##    67018    1.3595610e+02   0.000000e+00   0.000000e+00    213s
## 
## Root relaxation: objective 1.359561e+02, 67018 iterations, 76.26 seconds
## Total elapsed time = 215.99s
## 
##     Nodes    |    Current Node    |     Objective Bounds      |     Work
##  Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time
## 
##      0     0  135.95610    0  164  272.00000  135.95610  50.0%     -  216s
## H    0     0                     137.0000000  135.95610  0.76%     -  217s
## 
## Explored 0 nodes (79886 simplex iterations) in 217.95 seconds
## Thread count was 22 (of 24 available processors)
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 1.370000000000e+02, best bound 1.360000000000e+02, gap 0.7299%</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># show summary</span>
<span class="kw">summary</span>(cs_rs_space)</code></pre></div>
<pre><code>##   Run_Number  Status Score Cost Planning_Units Connectivity_Total
## 1          1 OPTIMAL   137  137            137           98882414
##   Connectivity_In Connectivity_Edge Connectivity_Out
## 1         9336021          80620163          8926230
##   Connectivity_In_Fraction
## 1               0.09441538</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot prioritisation</span>
<span class="kw">plot</span>(cs_rs_space,<span class="dv">1</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-58-1.png" title="plot of chunk unnamed-chunk-58" alt="plot of chunk unnamed-chunk-58" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot prioritisation in geographic attribute space</span>
p1 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_space, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dt">main=</span><span class="st">&#39;Blue-winged</span><span class="ch">\n</span><span class="st">kookaburra&#39;</span>)
p2 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_space, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dt">main=</span><span class="st">&#39;Brown-backed</span><span class="ch">\n</span><span class="st">honeyeater&#39;</span>)
p3 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_space, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dt">main=</span><span class="st">&#39;Brown falcon&#39;</span>)
p4 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_space, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dt">main=</span><span class="st">&#39;Pale-headed</span><span class="ch">\n</span><span class="st">rosella&#39;</span>)
gridExtra::<span class="kw">grid.arrange</span>(p1, p2, p3, p4, <span class="dt">ncol=</span><span class="dv">2</span>)</code></pre></div>
<div class="figure">
<img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-59-1.png" alt="Distribution of the amount- and space-based prioritisation in the geographic attribute space. See Figure 28 caption for conventions." />
<p class="caption"><em>Distribution of the amount- and space-based prioritisation in the geographic attribute space. See Figure 28 caption for conventions.</em></p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot prioritisation in environmental attribute space</span>
p1 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_space, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Blue-winged</span><span class="ch">\n</span><span class="st">kookaburra&#39;</span>)
p2 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_space, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Brown-backed</span><span class="ch">\n</span><span class="st">honeyeater&#39;</span>)
p3 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_space, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Brown falcon&#39;</span>)
p4 &lt;-<span class="st"> </span><span class="kw">space.plot</span>(cs_rs_space, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dt">main=</span><span class="st">&#39;Pale-headed</span><span class="ch">\n</span><span class="st">rosella&#39;</span>)
gridExtra::<span class="kw">grid.arrange</span>(p1, p2, p3, p4, <span class="dt">ncol=</span><span class="dv">2</span>)</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-60-1.png" title="_Distribution of the amount- and space-based prioritisation in the environmental attribute space. See Figure 28 caption for conventions._" alt="_Distribution of the amount- and space-based prioritisation in the environmental attribute space. See Figure 28 caption for conventions._" style="display: block; margin: auto;" /></p>
<p>Let’s compare these prioritisations with Queensland’s existing protected areas system. To do this, we can create update the <code>cs_rs_space</code> with manually specified solutions to create a <code>RapSolved</code> object to represent the Queensland’s reserve network.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># generate vector with Australia&#39;s selections</span>
aus_selections &lt;-<span class="st"> </span><span class="kw">which</span>(cs_pus$status&gt;<span class="dv">0</span>)

<span class="co"># create new object with Australia&#39;s network</span>
cs_rs_aus &lt;-<span class="st"> </span><span class="kw">update</span>(cs_rs_amount, <span class="dt">b=</span>aus_selections)</code></pre></div>
<p>Now, let’s plot the performance metrics for these prioritisations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define standard error function</span>
se=function(x){<span class="kw">sd</span>(x,<span class="dt">na.rm=</span><span class="ot">TRUE</span>)/<span class="kw">sqrt</span>(<span class="kw">sum</span>(!<span class="kw">is.na</span>(x)))}

<span class="co"># create a table to store the values for the 3 prioritisations</span>
cs_results &lt;-<span class="st"> </span><span class="kw">data.frame</span>(
    <span class="dt">name=</span><span class="kw">factor</span>(<span class="kw">rep</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&#39;Amount-based</span><span class="ch">\n</span><span class="st">prioritisation&#39;</span>, 
        <span class="st">&#39;Amount &amp; space-based</span><span class="ch">\n</span><span class="st">prioritisation&#39;</span>, <span class="st">&#39;Queensland reserve</span><span class="ch">\n</span><span class="st">network&#39;</span>),
        <span class="dt">each=</span><span class="dv">4</span>),<span class="dv">3</span>), <span class="dt">levels=</span><span class="kw">c</span>(<span class="kw">c</span>(<span class="st">&#39;Amount-based</span><span class="ch">\n</span><span class="st">prioritisation&#39;</span>, 
        <span class="st">&#39;Amount &amp; space-based</span><span class="ch">\n</span><span class="st">prioritisation&#39;</span>, <span class="st">&#39;Queensland reserve</span><span class="ch">\n</span><span class="st">network&#39;</span>))),
    <span class="dt">variable=</span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&#39;Amount&#39;</span>, <span class="st">&#39;Geographic space&#39;</span>, <span class="st">&#39;Environmental space&#39;</span>), <span class="dt">each=</span><span class="dv">12</span>),
    <span class="dt">species=</span><span class="kw">colnames</span>(<span class="kw">amount.held</span>(cs_rs_amount)),
    <span class="dt">value=</span><span class="kw">c</span>(
        <span class="kw">amount.held</span>(cs_rs_amount)[<span class="dv">1</span>,], <span class="kw">amount.held</span>(cs_rs_space)[<span class="dv">1</span>,],
            <span class="kw">amount.held</span>(cs_rs_aus)[<span class="dv">1</span>,],
        <span class="kw">space.held</span>(cs_rs_amount, <span class="dt">space=</span><span class="dv">2</span>)[<span class="dv">1</span>,], <span class="kw">space.held</span>(cs_rs_space, <span class="dt">space=</span><span class="dv">2</span>)[<span class="dv">1</span>,], 
            <span class="kw">space.held</span>(cs_rs_aus, <span class="dt">space=</span><span class="dv">2</span>)[<span class="dv">1</span>,],
        <span class="kw">space.held</span>(cs_rs_amount, <span class="dt">space=</span><span class="dv">1</span>)[<span class="dv">1</span>,], <span class="kw">space.held</span>(cs_rs_space, <span class="dt">space=</span><span class="dv">1</span>)[<span class="dv">1</span>,],
            <span class="kw">space.held</span>(cs_rs_aus, <span class="dt">space=</span><span class="dv">1</span>)[<span class="dv">1</span>,]
    )
) %&gt;%<span class="st"> </span><span class="kw">group_by</span>(name,variable) %&gt;%
<span class="st">    </span><span class="kw">summarise</span>(<span class="dt">mean=</span><span class="kw">mean</span>(value),<span class="dt">se=</span><span class="kw">se</span>(value))

<span class="co"># plot the performance metrics</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>variable, <span class="dt">y=</span>mean, <span class="dt">fill=</span>name), <span class="dt">data=</span>cs_results) +
<span class="st">    </span><span class="kw">geom_bar</span>(<span class="dt">position=</span><span class="kw">position_dodge</span>(<span class="fl">0.9</span>), <span class="dt">stat=</span><span class="st">&#39;identity&#39;</span>) +
<span class="st">    </span><span class="kw">geom_errorbar</span>(
        <span class="kw">aes</span>(<span class="dt">ymin=</span>mean-se, <span class="dt">ymax=</span>mean+se), <span class="dt">position=</span><span class="kw">position_dodge</span>(<span class="fl">0.9</span>),
        <span class="dt">width=</span><span class="fl">0.2</span>) +
<span class="st">    </span><span class="kw">xlab</span>(<span class="st">&#39;Property of species&#39;</span>) +
<span class="st">    </span><span class="kw">ylab</span>(<span class="st">&#39;Proportion held in</span><span class="ch">\n</span><span class="st">selected planning units (%)&#39;</span>) +
<span class="st">    </span><span class="kw">scale_fill_discrete</span>(<span class="dt">name=</span><span class="st">&#39;&#39;</span>) +
<span class="st">    </span><span class="kw">theme_classic</span>() +
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&#39;bottom&#39;</span>,<span class="dt">legend.direction=</span><span class="st">&#39;horizontal&#39;</span>,
        <span class="dt">axis.line.x=</span><span class="kw">element_line</span>(),<span class="dt">axis.line.y=</span><span class="kw">element_line</span>())</code></pre></div>
<p><img src="/home/uqjhans4/GitHub/raptr/vignettes/figure/unnamed-chunk-62-1.png" title="_Prioritisations were generated using amount-based targets (20\%), and with additional space-based targets (85\%). These are compared to the Queensland reserve network. Data represent means and standard errors for the four species in each prioritisation._" alt="_Prioritisations were generated using amount-based targets (20\%), and with additional space-based targets (85\%). These are compared to the Queensland reserve network. Data represent means and standard errors for the four species in each prioritisation._" style="display: block; margin: auto;" /> We can see that a greater number of planning units is needed to satisfy the space-based targets. The prioritisation generated using just amount-based targets has 136 planning units, and the prioritisations using amount-based and space-based targets has 137 planning units. These results suggest only a few additional planning units can result in significant improvements in the effectivenss of a prioritisation.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs toc">

        <div id="nav">
      <h2>Contents</h2>
      <ul>
      <li><a href="#overview">Overview</a></li>
      <li><a href="#getting-started">Getting started</a></li>
      <li><a href="#simulated-examples">Simulated examples</a><ul>
      <li><a href="#data">Data</a></li>
      <li><a href="#single-species-prioritisations">Single-species prioritisations</a><ul>
      <li><a href="#amount-based-targets">Amount-based targets</a></li>
      <li><a href="#amount-based-and-space-based-targets">Amount-based and space-based targets</a></li>
      </ul></li>
      <li><a href="#multi-species-prioritisations">Multi-species prioritisations</a><ul>
      <li><a href="#effects-of-including-space-based-targets">Effects of including space-based targets</a></li>
      <li><a href="#uncertainty-in-species-distributions">Uncertainty in species’ distributions</a></li>
      <li><a href="#fragmentation">Fragmentation</a></li>
      </ul></li>
      </ul></li>
      <li><a href="#case-study-examples">Case-study examples</a><ul>
      <li><a href="#introduction">Introduction</a></li>
      <li><a href="#data-1">Data</a></li>
      <li><a href="#analysis">Analysis</a></li>
      </ul></li>
      </ul>
    </div>
      </div>

</div>


<script>
$('#nav').affix({
  offset: {
    top: $('#nav').offset().top - 80
  }
});
</script>

        <footer>
        <p>Built by <a href="http://hadley.github.io/staticdocs/">staticdocs</a>. Styled with <a href="http://getbootstrap.com">Bootstrap 3</a>.</p>
        </footer>
   </div>

  </body>
</html>
