# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_append_modelfile <- function(model, existing_sols) {
    .Call('raspr_rcpp_append_modelfile', PACKAGE = 'raspr', model, existing_sols)
}

rcpp_calcBoundaryDF <- function(df, tolerance = 0.001, lengthFactor = 1.0, edgeFactor = 1.0) {
    .Call('raspr_rcpp_calcBoundaryDF', PACKAGE = 'raspr', df, tolerance, lengthFactor, edgeFactor)
}

rcpp_extract_model_results <- function(opts, data, model_file, log_file, solution_file) {
    .Call('raspr_rcpp_extract_model_results', PACKAGE = 'raspr', opts, data, model_file, log_file, solution_file)
}

rcpp_generate_modelfile <- function(opts, data) {
    .Call('raspr_rcpp_generate_modelfile', PACKAGE = 'raspr', opts, data)
}

rcpp_groupcombine <- function(group_means) {
    .Call('raspr_rcpp_groupcombine', PACKAGE = 'raspr', group_means)
}

rcpp_groupmean <- function(cat_vec, val_vec) {
    .Call('raspr_rcpp_groupmean', PACKAGE = 'raspr', cat_vec, val_vec)
}

rcpp_Polygons2PolySet <- function(polys, n_preallocate = 10000L) {
    .Call('raspr_rcpp_Polygons2PolySet', PACKAGE = 'raspr', polys, n_preallocate)
}

